/* TASNEEF v339 - stability fixes: contract view permissions, attendance filters, monthly print layout, finance reports and movement UI polish */
(function(){
  'use strict';
  if(window.__tasneefV339Stability) return; window.__tasneefV339Stability=true;
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const n=v=>Number(String(v??'').replace(/,/g,''))||0;
  const money=v=>n(v).toLocaleString('ar-SA',{minimumFractionDigits:2,maximumFractionDigits:2})+' ر.س';
  const LS={suppliers:'tasneef_v312_suppliers',items:'tasneef_v312_items',purchases:'tasneef_v312_purchases',moves:'tasneef_v312_moves',stocktakes:'tasneef_v326_stocktakes'};
  const parse=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||'null')||d}catch(_){return d}};
  const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const projects=()=>Array.isArray(window.data?.projects)?window.data.projects:[];
  const supervisors=()=>Array.isArray(window.data?.supervisors)?window.data.supervisors:[];
  const workers=()=>Array.isArray(window.data?.workers)?window.data.workers:[];
  const projectName=id=>{const p=projects().find(x=>String(x.id)===String(id));return p?(p.name||p.project_name||p.title||id):(id||'-')};
  const supervisorName=(id,fb='')=>{const s=supervisors().find(x=>String(x.id)===String(id));return s?(s.full_name||s.name||s.username||id):(fb||'-')};
  const itemById=id=>parse(LS.items).find(x=>String(x.id)===String(id))||{};
  const itemName=id=>itemById(id).name||'-';
  const itemCode=id=>itemById(id).code||itemById(id).company_code||'-';
  const itemUnit=id=>itemById(id).unit||'حبة';
  const supplierName=id=>{const s=parse(LS.suppliers).find(x=>String(x.id)===String(id));return s?s.name:'-'};
  const dateOf=v=>String(v||'').slice(0,10);
  const today=()=>new Date().toISOString().slice(0,10);
  const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
  const OUT_TYPES=new Set(['صرف','استهلاك','هدر','تالف','سكراب']);
  const MOVE_TYPES=['صرف','استهلاك','مرتجع','هدر','تالف','سكراب'];
  const approved=m=>['معتمد','تم الصرف'].includes(String(m.status||''));
  function showMsg(t,kind){ try{ if(typeof window.msg==='function') window.msg(t,kind); else alert(t); }catch(_){alert(t)} }

  /* ---------- Finance helper totals ---------- */
  function moveUnitCost(m){return n(m.unit_cost_override||m.unit_cost||itemById(m.item_id).price_after||itemById(m.item_id).price_after_vat||itemById(m.item_id).price||0)}
  function moveAmount(m){const a=n(m.amount||m.after||m.before||(n(m.qty)*moveUnitCost(m))); return a;}
  function moveSigned(m){return m.type==='مرتجع' ? -Math.abs(moveAmount(m)) : Math.abs(moveAmount(m));}
  function costTarget(m){const t=m.cost_type||'FM'; if(t==='FM') return projectName(m.project_id || (Array.isArray(m.project_ids)?m.project_ids[0]:'') || ''); if(t==='CN') return m.order_no||'-'; return m.general_note||m.notes||'عام';}
  function lineVatPartsFromUnit(unitAfter, qty, vatRate=15){ const after=n(unitAfter)*n(qty); const before=after/(1+n(vatRate)/100); return {before,vat:after-before,after}; }
  function purchaseTotals(lines){return (lines||[]).reduce((a,l)=>{a.before+=n(l.before);a.vat+=n(l.vat);a.after+=n(l.after);return a;},{before:0,vat:0,after:0});}
  function movementVatTotals(ms){return ms.reduce((a,m)=>{const it=itemById(m.item_id); const unit=n(m.unit_cost||m.unit_cost_override||it.price_after||it.price_after_vat||it.price||0); const vatRate=n(it.vat_rate||it.tax_rate||15); const p=lineVatPartsFromUnit(unit,n(m.qty),vatRate); const sign=m.type==='مرتجع'?-1:1; a.before+=sign*p.before; a.vat+=sign*p.vat; a.after+=sign*p.after; return a;},{before:0,vat:0,after:0});}
  function filters(){return {project:$('fiRProject')?.value||'',supervisor:$('fiRSupervisor')?.value||'',cost:$('fiRCost')?.value||'',from:$('fiRFrom')?.value||'',to:$('fiRTo')?.value||'',q:String($('fiRQ')?.value||'').trim().toLowerCase()};}
  function inDate(d,f){d=String(d||'').slice(0,10); if(f.from&&d<f.from)return false; if(f.to&&d>f.to)return false; return true;}
  function filteredMoves(includeReturns=true){const f=filters();return parse(LS.moves).filter(m=>{
    if(!includeReturns && m.type==='مرتجع') return false;
    if(!inDate(m.date,f))return false;
    if(f.cost&&String(m.cost_type||'FM')!==String(f.cost))return false;
    if(f.supervisor&&String(m.supervisor_id)!==String(f.supervisor))return false;
    if(f.project&&String(m.project_id||'')!==String(f.project))return false;
    if(f.q){const blob=[m.batch_no,m.type,m.status,m.notes,m.reason,itemName(m.item_id),itemCode(m.item_id),costTarget(m),supervisorName(m.supervisor_id,m.supervisor_name),m.order_no,m.general_note].join(' ').toLowerCase();if(!blob.includes(f.q))return false;}
    return true;
  });}
  function optionProjects(){return '<option value="">كل المشاريع</option>'+projects().map(p=>`<option value="${esc(p.id)}">${esc(p.name||p.project_name||p.title||p.id)}</option>`).join('')}
  function optionSup(){return '<option value="">كل المشرفين</option>'+supervisors().map(s=>`<option value="${esc(s.id)}">${esc(s.full_name||s.name||s.username||s.id)}</option>`).join('')}
  function reportHeader(title,sub){return `<div class="fi-r-head"><div><h3>${esc(title)}</h3><div class="fi-r-sub">${esc(sub||'')}</div></div><div class="fi-r-actions"><button class="primary" onclick="financeV339PrintReport()">طباعة PDF</button><button onclick="financeV339ExportCsv()">تصدير CSV</button></div></div>`}
  function vatSummary(t){return `<div class="fi-vat-summary"><div><small>السعر قبل الضريبة</small><b>${money(t.before)}</b></div><div><small>قيمة الضريبة</small><b>${money(t.vat)}</b></div><div><small>شامل الضريبة</small><b>${money(t.after)}</b></div></div>`}
  function ensureFinanceStyle(){if($('v339FinanceStyle'))return;const st=document.createElement('style');st.id='v339FinanceStyle';st.textContent=`
    .fi-vat-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin:14px 0}.fi-vat-summary>div{background:#fbfefd;border:1px solid #dbe9e4;border-radius:16px;padding:12px;text-align:center}.fi-vat-summary small{display:block;color:#6b7d77}.fi-vat-summary b{display:block;color:#064234;font-size:20px}.fi-r-toolbar .grid{grid-template-columns:repeat(6,minmax(0,1fr))}.fi-r-table-wrap{max-height:520px;overflow:auto}.v339-zero-note{background:#fff8e7;border:1px dashed #d6a941;border-radius:14px;padding:10px;margin:10px 0;color:#6e5000}.v339-plus{margin-inline-start:8px;border:0;border-radius:50%;width:34px;height:34px;background:#064234;color:#fff;font-weight:900;cursor:pointer}.v339-topline{display:flex;align-items:center;justify-content:space-between;gap:10px}.v339-line-actions{display:flex;gap:6px;flex-wrap:wrap}.contract-row-actions-v339{display:flex;gap:8px;justify-content:center}.visit-chip-v300{cursor:pointer!important}@media(max-width:900px){.fi-r-toolbar .grid,.fi-vat-summary{grid-template-columns:1fr}.fi-r-table{min-width:850px}}
  `;document.head.appendChild(st)}
  function renderReportsShell(){ensureFinanceStyle();const root=$('fiBody_reports')||$('financeBody')||$('fiContent')||document.querySelector('#finance .card'); if(!root)return; root.innerHTML=`<div class="fi-r-wrap"><div class="fi-r-toolbar"><div class="grid"><div><label>المشروع</label><select id="fiRProject">${optionProjects()}</select></div><div><label>المشرف</label><select id="fiRSupervisor">${optionSup()}</select></div><div><label>مركز التكلفة</label><select id="fiRCost"><option value="">كل المراكز</option><option value="FM">FM</option><option value="CN">CN</option><option value="GENERAL">GENERAL</option></select></div><div><label>من تاريخ</label><input type="date" id="fiRFrom"></div><div><label>إلى تاريخ</label><input type="date" id="fiRTo"></div><div><label>بحث</label><input id="fiRQ" placeholder="منتج، كود، مورد، حركة..."></div></div><div class="fi-r-actions"><button class="primary" onclick="financeV339ApplyFilters()">تطبيق الفلاتر</button><button onclick="financeV339ResetFilters()">إعادة تعيين</button><button onclick="financeV339PrintReport()">طباعة التقرير</button></div></div><div class="fi-r-nav"><button data-report="summary" onclick="financeV339OpenReport('summary')">ملخص شامل</button><button data-report="inventory" onclick="financeV339OpenReport('inventory')">تقرير المخزون</button><button data-report="stocktake" onclick="financeV339OpenReport('stocktake')">جرد المخزن</button><button data-report="suppliers" onclick="financeV339OpenReport('suppliers')">الموردين</button><button data-report="products" onclick="financeV339OpenReport('products')">المنتجات</button><button data-report="purchases" onclick="financeV339OpenReport('purchases')">فواتير الشراء</button><button data-report="movements" onclick="financeV339OpenReport('movements')">حركة المخزون</button><button data-report="costs" onclick="financeV339OpenReport('costs')">مركز التكلفة</button></div><div id="fiRReportBody" class="fi-r-main fi-r-print-area"></div></div>`;}
  function setBody(html){const b=$('fiRReportBody'); if(b)b.innerHTML=html;}
  function activeReport(k){document.querySelectorAll('.fi-r-nav button').forEach(b=>b.classList.toggle('active',b.dataset.report===k));localStorage.setItem('tasneef_v339_active_report',k)}
  function renderSummary(){const items=parse(LS.items), moves=filteredMoves(), purchases=parse(LS.purchases); const pTot=purchases.reduce((a,p)=>{const t=purchaseTotals(p.lines||[]); a.before+=t.before;a.vat+=t.vat;a.after+=t.after;return a},{before:0,vat:0,after:0}); const mTot=movementVatTotals(moves); const low=items.filter(i=>n(i.qty)>0 && n(i.qty)<=n(i.min_qty||i.alert_qty||i.min||0)).length; setBody(`${reportHeader('ملخص مالي ومخزون','أرقام مختصرة حسب الفلاتر')}
    <div class="fi-r-kpis"><div class="fi-r-kpi"><small>الموردين</small><b>${parse(LS.suppliers).length}</b></div><div class="fi-r-kpi"><small>الأصناف المتوفرة</small><b>${items.filter(i=>n(i.qty)>0).length}</b></div><div class="fi-r-kpi"><small>تنبيهات النقص</small><b>${low}</b></div><div class="fi-r-kpi"><small>حركات المخزون</small><b>${moves.length}</b></div></div>${vatSummary({before:pTot.before+mTot.before,vat:pTot.vat+mTot.vat,after:pTot.after+mTot.after})}<div class="v339-zero-note">التقارير تعرض المنتجات ذات الرصيد فقط في جرد المخزن، والمرتجع لا يدخل في تقرير مركز التكلفة.</div>`)}
  function renderInventory(){const rows=parse(LS.items).filter(i=>n(i.qty)>0).map(i=>`<tr><td><b>${esc(i.name||'-')}</b><br><small>${esc(i.category||'-')} / ${esc(i.unit||'')}</small></td><td>${esc(i.code||'-')}</td><td>${esc(i.company_code||'-')}</td><td>${n(i.qty)}</td><td>${money(n(i.price_before_vat||i.price_before||0))}</td><td>${money(n(i.price_vat||i.vat_value||0))}</td><td>${money(n(i.price_after_vat||i.price_after||i.price||0))}</td><td>${n(i.qty)<=n(i.min_qty||i.alert_qty||0)?'<span class="fi-r-chip warn">تنبيه</span>':'<span class="fi-r-chip ok">متوفر</span>'}</td></tr>`).join(''); const t=parse(LS.items).filter(i=>n(i.qty)>0).reduce((a,i)=>{a.before+=n(i.qty)*n(i.price_before_vat||i.price_before||0);a.vat+=n(i.qty)*n(i.price_vat||i.vat_value||0);a.after+=n(i.qty)*n(i.price_after_vat||i.price_after||i.price||0);return a},{before:0,vat:0,after:0}); setBody(`${reportHeader('تقرير المخزون','لا تظهر المنتجات المنتهية أو صفر في هذا التقرير')}${vatSummary(t)}<div class="fi-r-table-wrap"><table class="fi-r-table"><thead><tr><th>المنتج</th><th>الكود</th><th>كود الشركة</th><th>المتبقي</th><th>قبل</th><th>ضريبة</th><th>شامل</th><th>تنبيه</th></tr></thead><tbody>${rows||'<tr><td colspan="8"><div class="fi-r-empty">لا توجد منتجات متوفرة</div></td></tr>'}</tbody></table></div>`)}
  function renderStocktake(){const items=parse(LS.items).filter(i=>n(i.qty)>0); const rows=items.map(i=>`<tr data-stock-item="${esc(i.id)}"><td><b>${esc(i.name||'-')}</b><br><small>${esc(i.code||'-')}</small></td><td>${esc(i.unit||'')}</td><td>${n(i.qty)}</td><td><input class="fi-r-stock-input" type="number" step="0.01" value="${n(i.qty)}"></td><td><input class="fi-r-note-input" placeholder="ملاحظات الجرد"></td></tr>`).join(''); const t=items.reduce((a,i)=>{a.before+=n(i.qty)*n(i.price_before_vat||i.price_before||0);a.vat+=n(i.qty)*n(i.price_vat||i.vat_value||0);a.after+=n(i.qty)*n(i.price_after_vat||i.price_after||i.price||0);return a},{before:0,vat:0,after:0}); setBody(`${reportHeader('جرد المخزن','المنتجات ذات الرصيد صفر لا تظهر في الجرد')}${vatSummary(t)}<div class="fi-r-actions"><button class="primary" onclick="financeV339SaveStocktake()">حفظ محضر الجرد</button></div><div class="fi-r-table-wrap"><table class="fi-r-table"><thead><tr><th>المنتج</th><th>الوحدة</th><th>كمية النظام</th><th>كمية الجرد</th><th>ملاحظات</th></tr></thead><tbody>${rows||'<tr><td colspan="5"><div class="fi-r-empty">لا توجد منتجات للجرد</div></td></tr>'}</tbody></table></div>`)}
  function renderSuppliers(){const purchases=parse(LS.purchases); const rows=parse(LS.suppliers).map(s=>{const ps=purchases.filter(p=>String(p.supplier_id)===String(s.id));const t=ps.reduce((a,p)=>{const x=purchaseTotals(p.lines||[]);a.before+=x.before;a.vat+=x.vat;a.after+=x.after;return a},{before:0,vat:0,after:0});return `<tr><td><b>${esc(s.name||'-')}</b><br><small>${esc(s.vat||'')}</small></td><td>${esc(s.phone||'-')}</td><td>${esc(s.type||'-')}</td><td>${ps.length}</td><td>${money(t.before)}</td><td>${money(t.vat)}</td><td>${money(t.after)}</td><td>${esc(s.status||'نشط')}</td></tr>`}).join(''); const all=parse(LS.purchases).reduce((a,p)=>{const x=purchaseTotals(p.lines||[]);a.before+=x.before;a.vat+=x.vat;a.after+=x.after;return a},{before:0,vat:0,after:0}); setBody(`${reportHeader('تقرير الموردين','مشتريات كل مورد')}${vatSummary(all)}<div class="fi-r-table-wrap"><table class="fi-r-table"><thead><tr><th>المورد</th><th>الجوال</th><th>النوع</th><th>الفواتير</th><th>قبل</th><th>ضريبة</th><th>شامل</th><th>الحالة</th></tr></thead><tbody>${rows||'<tr><td colspan="8"><div class="fi-r-empty">لا توجد بيانات</div></td></tr>'}</tbody></table></div>`)}
  function renderProducts(){const f=filters(); let items=parse(LS.items); if(f.q)items=items.filter(i=>[i.name,i.code,i.company_code,i.category,i.unit].join(' ').toLowerCase().includes(f.q)); const moves=parse(LS.moves); const purchases=parse(LS.purchases); const rows=items.map(i=>{let inQty=0; purchases.forEach(p=>(p.lines||[]).forEach(l=>{if(String(l.item_id)===String(i.id))inQty+=n(l.qty)})); const im=moves.filter(m=>String(m.item_id)===String(i.id)); const out=im.filter(m=>OUT_TYPES.has(m.type)).reduce((a,m)=>a+n(m.qty),0), ret=im.filter(m=>m.type==='مرتجع').reduce((a,m)=>a+n(m.qty),0), cons=im.filter(m=>m.type==='استهلاك').reduce((a,m)=>a+n(m.qty),0); return `<tr><td><b>${esc(i.name||'-')}</b><br><small>${esc(i.category||'-')} / ${esc(i.unit||'')}</small></td><td>${esc(i.code||'-')}</td><td>${inQty}</td><td>${out}</td><td>${cons}</td><td>${ret}</td><td>${n(i.qty)}</td><td>${money(n(i.price_before_vat||i.price_before||0))}</td><td>${money(n(i.price_vat||i.vat_value||0))}</td><td>${money(n(i.price_after_vat||i.price_after||i.price||0))}</td></tr>`}).join(''); const t=items.reduce((a,i)=>{a.before+=n(i.qty)*n(i.price_before_vat||i.price_before||0);a.vat+=n(i.qty)*n(i.price_vat||i.vat_value||0);a.after+=n(i.qty)*n(i.price_after_vat||i.price_after||i.price||0);return a},{before:0,vat:0,after:0}); setBody(`${reportHeader('تقرير المنتجات','الدخل والخرج والمرتجع والمتبقي')}${vatSummary(t)}<div class="fi-r-table-wrap"><table class="fi-r-table"><thead><tr><th>المنتج</th><th>الكود</th><th>دخل</th><th>خرج</th><th>مستهلك</th><th>مرتجع</th><th>متبقي</th><th>قبل</th><th>ضريبة</th><th>شامل</th></tr></thead><tbody>${rows||'<tr><td colspan="10"><div class="fi-r-empty">لا توجد بيانات</div></td></tr>'}</tbody></table></div>`)}
  function renderPurchases(){let ps=parse(LS.purchases).filter(p=>inDate(p.date,filters())); const f=filters(); if(f.q)ps=ps.filter(p=>[p.invoice_no,supplierName(p.supplier_id),p.notes].join(' ').toLowerCase().includes(f.q)); const rows=ps.map(p=>{const t=purchaseTotals(p.lines||[]);return `<tr><td><b>${esc(p.invoice_no||p.id)}</b><br><small>${esc(p.date||'')}</small></td><td>${esc(supplierName(p.supplier_id))}</td><td>${(p.lines||[]).length}</td><td>${money(t.before)}</td><td>${money(t.vat)}</td><td>${money(t.after)}</td><td>${esc(p.file_name||'-')}</td></tr>`}).join(''); const all=ps.reduce((a,p)=>{const x=purchaseTotals(p.lines||[]);a.before+=x.before;a.vat+=x.vat;a.after+=x.after;return a},{before:0,vat:0,after:0}); setBody(`${reportHeader('تقرير فواتير الشراء','حسب الفلاتر')}${vatSummary(all)}<div class="fi-r-table-wrap"><table class="fi-r-table"><thead><tr><th>الفاتورة</th><th>المورد</th><th>الأصناف</th><th>قبل</th><th>ضريبة</th><th>شامل</th><th>المرفق</th></tr></thead><tbody>${rows||'<tr><td colspan="7"><div class="fi-r-empty">لا توجد فواتير</div></td></tr>'}</tbody></table></div>`)}
  function renderMovements(){const ms=filteredMoves(true); const rows=ms.map(m=>`<tr><td><b>${esc(m.batch_no||m.id)}</b><br><small>${esc(m.date||'')}</small></td><td>${esc(supervisorName(m.supervisor_id,m.supervisor_name))}</td><td><b>${esc(itemName(m.item_id))}</b><br><small>${esc(itemCode(m.item_id))}</small></td><td>${n(m.qty)} ${esc(itemUnit(m.item_id))}</td><td>${esc(m.type||'-')}</td><td>${esc(m.cost_type||'FM')}</td><td>${esc(costTarget(m))}</td><td>${money(moveSigned(m))}</td><td>${esc(m.status||'-')}</td></tr>`).join(''); const t=movementVatTotals(ms); setBody(`${reportHeader('تقرير حركة المخزون','يشمل الصرف والاستهلاك والمرتجع')}${vatSummary(t)}<div class="fi-r-table-wrap"><table class="fi-r-table"><thead><tr><th>الحركة</th><th>المشرف</th><th>المنتج</th><th>الكمية</th><th>النوع</th><th>المركز</th><th>الوجهة</th><th>التكلفة</th><th>الحالة</th></tr></thead><tbody>${rows||'<tr><td colspan="9"><div class="fi-r-empty">لا توجد حركات</div></td></tr>'}</tbody></table></div>`)}
  function renderCosts(){const ms=filteredMoves(false); const agg={}; ms.forEach(m=>{const k=[m.cost_type||'FM',costTarget(m)].join('::'); if(!agg[k])agg[k]={cost_type:m.cost_type||'FM',target:costTarget(m),qty:0,cost:0,items:{}}; agg[k].qty+=n(m.qty); agg[k].cost+=Math.abs(moveAmount(m)); const nm=itemName(m.item_id);agg[k].items[nm]=(agg[k].items[nm]||0)+n(m.qty)}); const rows=Object.values(agg).sort((a,b)=>b.cost-a.cost).map(a=>`<tr><td><span class="fi-r-chip">${esc(a.cost_type)}</span></td><td><b>${esc(a.target)}</b></td><td>${a.qty}</td><td>${money(a.cost)}</td><td>${Object.entries(a.items).map(([k,v])=>`${esc(k)}: ${v}`).join('<br>')}</td></tr>`).join(''); const total=Object.values(agg).reduce((a,x)=>a+x.cost,0); setBody(`${reportHeader('تقرير مركز التكلفة','لا يدخل المرتجع في هذا التقرير')}${vatSummary(lineVatPartsFromUnit(total,1,15))}<div class="fi-r-table-wrap"><table class="fi-r-table"><thead><tr><th>المركز</th><th>الوجهة</th><th>الكمية</th><th>التكلفة</th><th>تفصيل الأصناف</th></tr></thead><tbody>${rows||'<tr><td colspan="5"><div class="fi-r-empty">لا توجد بيانات تكلفة</div></td></tr>'}</tbody></table></div>`)}
  window.financeV339OpenReport=function(k){ensureFinanceStyle(); activeReport(k); ({summary:renderSummary,inventory:renderInventory,stocktake:renderStocktake,suppliers:renderSuppliers,products:renderProducts,purchases:renderPurchases,movements:renderMovements,costs:renderCosts}[k]||renderSummary)();};
  window.financeV339ApplyFilters=function(){financeV339OpenReport(localStorage.getItem('tasneef_v339_active_report')||'summary')};
  window.financeV339ResetFilters=function(){['fiRProject','fiRSupervisor','fiRCost','fiRFrom','fiRTo','fiRQ'].forEach(id=>{if($(id))$(id).value=''});financeV339ApplyFilters()};
  window.financeV339SaveStocktake=function(){const rows=[...document.querySelectorAll('tr[data-stock-item]')].map(tr=>({item_id:tr.dataset.stockItem,system_qty:n(tr.children[2].textContent),counted_qty:n(tr.querySelector('.fi-r-stock-input')?.value),notes:tr.querySelector('.fi-r-note-input')?.value||'',date:new Date().toISOString()}));const arr=parse(LS.stocktakes);arr.push({id:uid(),date:new Date().toISOString(),rows});save(LS.stocktakes,arr);showMsg('تم حفظ محضر الجرد')};
  window.financeV339PrintReport=function(){const title=$('fiRReportBody')?.querySelector('h3')?.textContent||'تقرير المالية والمخزون';const html=$('fiRReportBody')?.innerHTML||'';const w=window.open('','_blank');w.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>${esc(title)}</title><style>body{font-family:Tahoma,Arial;margin:20px;color:#063d31}.head{display:flex;justify-content:space-between;align-items:center;border-bottom:3px solid #064234;padding-bottom:12px;margin-bottom:14px}.head img{height:58px}.fi-r-actions,.fi-r-nav,.fi-r-toolbar{display:none!important}.fi-vat-summary,.fi-r-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:10px 0}.fi-vat-summary>div,.fi-r-kpi{border:1px solid #dfece7;border-radius:12px;padding:9px;text-align:center}.fi-r-table{width:100%;border-collapse:collapse;font-size:11px}.fi-r-table th{background:#eef7f3;color:#063d31}.fi-r-table th,.fi-r-table td{border:1px solid #dfece7;padding:6px;text-align:right}.fi-r-table-wrap{overflow:visible}.fi-r-chip{display:inline-block;border-radius:20px;background:#eef7f3;padding:3px 7px}@media print{body{margin:8mm}}</style></head><body><div class="head"><div><h1>${esc(title)}</h1><div>تاريخ الطباعة: ${new Date().toLocaleString('ar-SA')}</div></div><img src="tasneef_logo_print.png" onerror="this.style.display='none'"></div>${html}<script>window.onload=function(){setTimeout(function(){window.print()},300)}<\/script></body></html>`);w.document.close()};
  window.financeV339ExportCsv=function(){const table=$('fiRReportBody')?.querySelector('table');if(!table)return showMsg('لا يوجد جدول للتصدير','err');const rows=[...table.querySelectorAll('tr')].map(tr=>[...tr.children].map(td=>'"'+String(td.innerText||'').replace(/"/g,'""').replace(/\n/g,' ')+'"').join(','));const blob=new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='tasneef-report.csv';a.click();URL.revokeObjectURL(a.href)};
  window.financeV326OpenReport=window.financeV339OpenReport; window.financeV326ApplyFilters=window.financeV339ApplyFilters; window.financeV326ResetFilters=window.financeV339ResetFilters; window.financeV326PrintReport=window.financeV339PrintReport; window.financeV326ExportCurrentCsv=window.financeV339ExportCsv;
  const oldFinanceTab=window.financeV312Tab; window.financeV312Tab=function(tab,btn){const r=oldFinanceTab?oldFinanceTab.apply(this,arguments):undefined;if(tab==='reports')setTimeout(()=>{renderReportsShell();financeV339OpenReport(localStorage.getItem('tasneef_v339_active_report')||'summary')},80);return r};

  /* ---------- Movement product view polish: plus beside product ---------- */
  const oldV337Open=window.v337OpenMove;
  window.v337OpenMove=function(id){const r=oldV337Open?oldV337Open.apply(this,arguments):undefined;setTimeout(()=>{document.querySelectorAll('.v337-product-head').forEach(head=>{if(head.querySelector('.v339-plus'))return;const product=head.closest('.v337-product');const add=product?.querySelector('.v337-add');const btn=document.createElement('button');btn.className='v339-plus';btn.title='إضافة توزيع للمنتج';btn.textContent='+';btn.onclick=()=>add&&add.scrollIntoView({behavior:'smooth',block:'center'});head.querySelector('.v337-title')?.appendChild(btn)});},80);return r}; window.v334ViewMove=window.v337OpenMove; window.v335OpenMove=window.v337OpenMove; window.v336OpenMove=window.v337OpenMove;

  /* ---------- Contracts: ordinary admins view only, system manager can edit; view can mark visits ---------- */
  function isSystemManager(){const u=(typeof session==='function'?session():null)||{}; const s=[u.username,u.full_name,u.role].join(' '); return u.role==='admin' && (/admin|مدير النظام|system/i.test(s));}
  function contractInfoLocal(p){if(typeof window.contractInfo==='function')try{return window.contractInfo(p)}catch(_){} const end=p.contract_end; if(!end)return {key:'missing',text:'غير محدد',days:'-',cls:'amber'}; const d=Math.ceil((new Date(end)-new Date())/86400000); return {key:d<0?'expired':d<=30?'soon':'active',text:d<0?'منتهي':d<=30?'قريب الانتهاء':'نشط',days:d+' يوم',cls:d<0?'red':d<=30?'amber':'green'};}
  window.forceRenderContractsV300=function(){const body=$('contractsBody'); if(!body)return; const q=($('contractSearch')?.value||'').trim(); const st=$('contractFilterStatus')?.value||''; let rows=projects().slice(); if(q)rows=rows.filter(p=>String(p.name||'').includes(q)); if(st)rows=rows.filter(p=>contractInfoLocal(p).key===st); rows.sort((a,b)=>new Date(a.contract_end||'2999-01-01')-new Date(b.contract_end||'2999-01-01')); const canEdit=isSystemManager(); body.innerHTML=rows.map(p=>{const c=contractInfoLocal(p);return `<tr><td><b>${esc(p.name||'')}</b></td><td>${p.buildings_count||0}</td><td>${p.units_count||0}</td><td>${esc(String(p.contract_start||'').slice(0,10)||'-')}</td><td>${esc(String(p.contract_end||'').slice(0,10)||'-')}</td><td>${esc(c.days)}</td><td><span class="badge ${esc(c.cls)}">${esc(c.text)}</span></td><td><div class="contract-row-actions-v339"><button type="button" class="light" onclick="openContractSmartModalV300('${esc(p.id)}','view')">عرض</button>${canEdit?`<button type="button" onclick="openContractSmartModalV300('${esc(p.id)}','edit')">تعديل</button>`:''}</div></td></tr>`}).join('')||'<tr><td colspan="8">لا توجد بيانات</td></tr>'};
  const oldContractOpen=window.openContractSmartModalV300;
  window.openContractSmartModalV300=function(id,mode){ const canEdit=isSystemManager(); const viewMode=(mode==='view'&&!canEdit); const r=oldContractOpen?oldContractOpen(id, viewMode?'edit':mode):undefined; setTimeout(()=>{ if(viewMode){ $('csSaveV300')&&( $('csSaveV300').style.display='none'); const modal=$('contractSmartModalV300'); modal?.querySelectorAll('input,select,textarea').forEach(x=>{ if(x.closest('.visit-boxes-v300')) return; x.disabled=true; }); modal?.querySelectorAll('.visit-chip-v300').forEach(b=>{b.disabled=false; b.removeAttribute('disabled')}); const note=document.createElement('div'); note.className='smart-alert-v300'; note.textContent='وضع العرض: يمكن تسجيل تنفيذ الزيارات فقط، ولا يمكن تعديل بيانات العقد.'; $('contractAlertPortalsV309')?.before(note); } },90); return r; };
  const oldToggle=window.toggleCoreVisitV300;
  window.toggleCoreVisitV300=function(key,no){ const u=(typeof session==='function'?session():null)||{}; if(oldToggle){ try{ const mod=$('contractSmartModalV300'); mod?.querySelectorAll('.core-card-v300 input,.core-card-v300 select,.core-card-v300 textarea').forEach(x=>{ if(!x.closest('.visit-boxes-v300')) x.disabled=false; }); return oldToggle(key,no); }catch(e){console.warn(e)} } };

  /* ---------- Attendance monthly supervisor filter fix ---------- */
  function workerSup(w){try{return typeof workerSupId==='function'?workerSupId(w):(w.supervisor_id||w.supervisorId)}catch(_){return w.supervisor_id||''}}
  function workerProj(w){try{return typeof workerProjectId==='function'?workerProjectId(w):(w.project_id||w.projectId)}catch(_){return w.project_id||''}}
  function monthDays(m){const [y,mo]=String(m||today().slice(0,7)).split('-').map(Number);return new Date(y,mo,0).getDate()}
  function fillKeep(id,rows,label,all){const el=$(id);if(!el)return '';const old=el.value||'';el.innerHTML=`<option value="">${all}</option>`+(rows||[]).map(r=>`<option value="${esc(r.id)}">${esc(label(r))}</option>`).join(''); if([...el.options].some(o=>o.value===old))el.value=old;return el.value||''}
  window.renderAttendanceMonthly=function(){const body=$('attendanceMatrixBody');if(!body)return;const month=$('attendanceMatrixMonth')?.value||today().slice(0,7);const sid=fillKeep('attendanceMatrixSupervisor',supervisors(),s=>s.full_name||s.name||s.username,'كل المشرفين');const pros=sid?projects().filter(p=>String(p.supervisor_id)===String(sid)||workers().some(w=>String(workerSup(w))===String(sid)&&String(workerProj(w))===String(p.id))):projects();const pid=fillKeep('attendanceMatrixProject',pros,p=>p.name||p.project_name||p.title,'كل المشاريع');const q=($('attendanceMatrixSearch')?.value||'').trim();const days=monthDays(month);const rows=workers().filter(w=>{const att=(window.data?.attendance||[]).filter(a=>String(a.worker_id)===String(w.id)&&String(a.attendance_date||'').slice(0,7)===month);if(sid&&String(workerSup(w))!==String(sid)&&!att.some(a=>String(a.supervisor_id)===String(sid)))return false;if(pid&&String(workerProj(w))!==String(pid)&&!att.some(a=>String(a.project_id)===String(pid)))return false;if(q&&!String(w.name||'').includes(q))return false;return true});const head=$('attendanceMatrixHead');if(head)head.innerHTML='<tr><th>الاسم</th><th>النوع</th><th>المشرف</th>'+Array.from({length:days},(_,i)=>`<th>${String(i+1).padStart(2,'0')}</th>`).join('')+'<th>حضور</th><th>غياب</th><th>النسبة</th></tr>';let pTot=0,aTot=0;body.innerHTML=rows.map(w=>{let pr=0,ab=0;const cells=[];for(let d=1;d<=days;d++){const ds=month+'-'+String(d).padStart(2,'0');const rec=(window.data?.attendance||[]).find(a=>String(a.worker_id)===String(w.id)&&a.attendance_date===ds&&(!sid||String(a.supervisor_id||workerSup(w))===String(sid))&&(!pid||String(a.project_id||workerProj(w))===String(pid)));if(rec?.status==='present'){pr++;cells.push('<td><span class="att-cell att-present">ح</span></td>')}else if(rec?.status==='absent'){ab++;cells.push('<td><span class="att-cell att-absent">غ</span></td>')}else cells.push('<td><span class="att-cell att-empty">-</span></td>')}pTot+=pr;aTot+=ab;const pct=(pr+ab)?pr/(pr+ab)*100:0;return `<tr><td><b>${esc(w.name||'-')}</b></td><td>${esc(w.worker_type==='technician'?'فني':'عامل')}</td><td>${esc(supervisorName(sid||workerSup(w)))}</td>${cells.join('')}<td>${pr}</td><td>${ab}</td><td>${pct.toFixed(1)}%</td></tr>`}).join('')||`<tr><td colspan="${days+6}">لا توجد بيانات حسب الفلاتر</td></tr>`;const rec=pTot+aTot;if($('attendanceMatrixSummary'))$('attendanceMatrixSummary').innerHTML=`<div class="kpi"><small>عدد الأسماء</small><b>${rows.length}</b></div><div class="kpi"><small>إجمالي الحضور</small><b>${pTot}</b></div><div class="kpi"><small>إجمالي الغياب</small><b>${aTot}</b></div><div class="kpi"><small>نسبة الحضور</small><b>${(rec?pTot/rec*100:0).toFixed(1)}%</b></div>`};
  ['attendanceMatrixMonth','attendanceMatrixSupervisor','attendanceMatrixProject','attendanceMatrixSearch'].forEach(id=>document.addEventListener('change',e=>{if(e.target&&e.target.id===id)setTimeout(()=>window.renderAttendanceMonthly(),10)},true));
  document.addEventListener('input',e=>{if(e.target&&e.target.id==='attendanceMatrixSearch')setTimeout(()=>window.renderAttendanceMonthly(),10)},true);

  /* ---------- Monthly print layout matching supervisor boxes/daily/fixed style ---------- */
  function mLabel(m){const a=String(m||'').split('-');return a.length===2?`${a[1]}-${a[0]}`:m}
  function minsText(x){return typeof minsToText==='function'?minsToText(x):(Math.floor(n(x)/60)+' ساعة '+(n(x)%60)+' دقيقة')}
  function monthlyRows(){const month=$('monthlyMonth')?.value||today().slice(0,7), sid=$('monthlySupervisor')?.value||''; let logs=(window.data?.logs||[]).filter(l=>String(l.visit_type||'')!=='technician_attendance'&&String(l.log_date||l.check_in||'').slice(0,7)===month); if(sid)logs=logs.filter(l=>String(l.supervisor_id)===String(sid));const map={};logs.forEach(l=>{const k=(l.supervisor_id||'')+'__'+(l.project_id||'');if(!map[k])map[k]={sid:l.supervisor_id,pid:l.project_id,actual:0,req:0,travel:0,count:0};const x=map[k];x.count++;x.actual+=n(l.duration_minutes||(typeof minutesBetween==='function'?minutesBetween(l.check_in,l.check_out):0));x.req+=n(l.required_minutes||(typeof requiredMinutesForLog==='function'?requiredMinutesForLog(l.project_id,l.log_date):0));x.travel+=n(l.travel_minutes)});return Object.values(map).map(x=>{x.percent=x.req?x.actual/x.req*100:0;return x})}
  function workerTextForProject(pid,sid){const names=workers().filter(w=>(!pid||String(workerProj(w))===String(pid))&&(!sid||String(workerSup(w))===String(sid))).map(w=>w.name).filter(Boolean);return names.join('، ')||'-'}
  window.printMonthlyReportV57=function(){const rows=monthlyRows(); if(!rows.length)return showMsg('لا توجد بيانات للطباعة','err');const month=$('monthlyMonth')?.value||today().slice(0,7);const groups={}; rows.forEach(r=>{const k=r.sid||''; if(!groups[k])groups[k]=[];groups[k].push(r)});const cards=Object.entries(groups).map(([sid,arr])=>{const items=arr.map(r=>`<tr><td>${esc(projectName(r.pid))}</td><td>${minsText(r.actual)}</td><td>${r.percent.toFixed(1)}%</td></tr>`).join('');const fixed=arr.filter(r=>r.req>=480).map(r=>`<div class="fixed-proj"><b>${esc(projectName(r.pid))}</b><span>${minsText(r.actual)}</span><small>${r.percent.toFixed(1)}%</small></div>`).join('')||'<div class="muted">لا توجد مشاريع دائمة محددة</div>';return `<div class="sup-box"><h3>${esc(supervisorName(sid))}</h3><h4>مشاريع الزيارة اليومية</h4><table><thead><tr><th>المشروع</th><th>الوقت</th><th>النسبة</th></tr></thead><tbody>${items}</tbody></table><div class="workers"><b>أسماء العمال</b><p>${esc(workerTextForProject('',sid))}</p></div><h4>مشاريع العمالة الدائمة</h4><div class="fixed-grid">${fixed}</div></div>`}).join('');const html=`<!doctype html><html dir="rtl" lang="ar"><head><meta charset="utf-8"><title>تقرير الأوقات الشهرية</title><style>@page{size:A4 landscape;margin:8mm}body{font-family:Tahoma,Arial;color:#063d31;margin:0}.top{display:flex;justify-content:space-between;align-items:center;border-bottom:3px solid #063d31;padding:12px 0;margin-bottom:14px}.top h1{font-size:30px;margin:0}.meta{text-align:center;font-size:16px;margin:10px 0}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.sup-box{border:2px solid #111;padding:10px;min-height:260px;break-inside:avoid}.sup-box h3{text-align:center;margin:0 0 6px}.sup-box h4{text-align:center;margin:8px 0 5px;color:#063d31}table{width:100%;border-collapse:collapse;font-size:12px}th,td{border:1px solid #111;padding:4px;text-align:center}.workers{text-align:center;margin-top:10px}.workers p{line-height:1.7}.fixed-grid{display:flex;flex-wrap:wrap;gap:5px;justify-content:center}.fixed-proj{border:1px solid #111;padding:4px 8px;min-width:80px;text-align:center}.fixed-proj b,.fixed-proj span,.fixed-proj small{display:block}.muted{color:#777;text-align:center}.foot{margin-top:18px;display:flex;justify-content:space-between}@media print{body{print-color-adjust:exact;-webkit-print-color-adjust:exact}}</style></head><body><div class="top"><h2>شركة تصنيف لإدارة المرافق</h2><button onclick="window.print()">طباعة</button></div><h1>تقرير الأوقات الشهرية</h1><div class="meta">الشهر: ${esc(mLabel(month))}</div><div class="grid">${cards}</div><div class="foot"><div>اعتماد مدير التشغيل: ____________</div><div>التوقيع: ____________</div></div><script>window.onload=function(){setTimeout(function(){window.print()},350)}<\/script></body></html>`;const w=window.open('','_blank');w.document.open();w.document.write(html);w.document.close()};

  /* install on load */
  setTimeout(()=>{try{forceRenderContractsV300()}catch(_){};try{if($('fiBody_reports')?.classList.contains('active')){renderReportsShell();financeV339OpenReport('summary')}}catch(_){};try{window.renderAttendanceMonthly&&window.renderAttendanceMonthly()}catch(_){}},700);
})();
