-- Tasneef Orders Unified v10400
-- آمن على البيانات: لا يحذف ولا يعدّل أي سجل موجود في orders_shared.
-- ينشئ فقط جدول سجل التعديلات والفهارس والسياسات اللازمة.

create table if not exists public.order_audit_logs (
  id bigint generated by default as identity primary key,
  order_no text not null,
  action_type text not null check (action_type in ('create','update','delete','status_change','receipt_change','other')),
  field_name text,
  field_label text,
  old_value text,
  new_value text,
  changed_by_id text,
  changed_by_name text not null default 'مستخدم النظام',
  changed_by_role text,
  changed_at timestamptz not null default now()
);

create index if not exists order_audit_logs_order_no_idx on public.order_audit_logs(order_no);
create index if not exists order_audit_logs_changed_at_idx on public.order_audit_logs(changed_at desc);

alter table public.order_audit_logs enable row level security;

drop policy if exists "orders audit select" on public.order_audit_logs;
create policy "orders audit select" on public.order_audit_logs for select using (true);

drop policy if exists "orders audit insert" on public.order_audit_logs;
create policy "orders audit insert" on public.order_audit_logs for insert with check (true);

-- لا توجد أوامر DELETE أو UPDATE على orders_shared في هذا السكربت.
-- بيانات الأوردرات القديمة تبقى كما هي، والحقول الجديدة تحفظ داخل عمود data JSON فقط عند تعديل السجل نفسه.
