(function(){
  'use strict';
  if(window.__tasneefInventoryAuditRootV10046) return;
  window.__tasneefInventoryAuditRootV10046 = true;
  const $=id=>document.getElementById(id); const S=v=>String(v??'').trim(); const N=v=>Number(v||0)||0;
  function say(t,type){ try{ if(typeof msg==='function') msg(t,type); else alert(t); }catch(_){ alert(t); } }
  function ensureSection(){
    if($('inventoryAudit')) return;
    const main=document.querySelector('main.content')||document.querySelector('main')||document.body;
    const sec=document.createElement('section'); sec.id='inventoryAudit'; sec.className='page hidden';
    sec.innerHTML=`<div class="card section-head"><div><h2>الجرد</h2><p>جرد مستقل مربوط بالمالية والمخزون. عند وجود جرد مفتوح يتم قفل حركات المالية والمخزون حتى إغلاق الجرد.</p></div><button onclick="tasneefInventoryAuditV10046.newAudit()">+ عملية جرد جديدة</button></div><div id="auditLockMsgV10046" class="msg hidden"></div><div class="card"><div class="table-head"><h2>عمليات الجرد</h2><div class="row-actions"><button class="light" onclick="tasneefInventoryAuditV10046.load()">تحديث</button><button class="light" onclick="tasneefInventoryAuditV10046.print()">طباعة</button><button class="light" onclick="tasneefInventoryAuditV10046.exportCsv()">تصدير CSV</button></div></div><div id="auditSessionsV10046" class="quick-list"></div></div><div class="card"><div class="table-head"><h2 id="auditTitleV10046">تفاصيل الجرد</h2><div class="row-actions"><button class="light" onclick="tasneefInventoryAuditV10046.closeAudit(false)">إغلاق بدون تعديل المخزون</button></div></div><div class="table-wrap"><table><thead><tr><th>المنتج</th><th>كود المنتج</th><th>كود الموزع</th><th>الوحدة</th><th>كمية النظام</th><th>الكمية الفعلية</th><th>الفرق</th><th>الحالة</th><th>ملاحظات</th></tr></thead><tbody id="auditItemsBodyV10046"></tbody></table></div></div>`;
    main.appendChild(sec);
  }
  async function openAudit(){ if(!window.sb) return null; try{ const r=await sb.from('inventory_audit_sessions').select('*').eq('status','open').order('id',{ascending:false}).limit(1).maybeSingle(); return r.data||null; }catch(_){return null;} }
  async function getProducts(){
    if(!window.sb) return [];
    const tries=[
      ['inventory_balance_v10020','*'],['inventory_items','*'],['inventory_products','*']
    ];
    for(const [table,cols] of tries){ try{ const r=await sb.from(table).select(cols).limit(2000); if(!r.error && Array.isArray(r.data) && r.data.length) return r.data; }catch(_){} }
    return Array.isArray(window.data?.inventoryItems)?window.data.inventoryItems:[];
  }
  function productRow(p){ const name=p.product_name||p.name||p.item_name||p.title||''; const code=p.product_code||p.code||p.internal_code||p.id||''; const dist=p.distributor_code||p.supplier_code||p.vendor_code||''; const unit=p.unit||p.measure_unit||''; const qty=N(p.current_qty??p.quantity??p.balance??p.stock_qty??p.available_qty); return {product_id:S(p.id||code||name), product_code:S(code), distributor_code:S(dist), product_name:S(name), unit:S(unit), system_qty:qty, actual_qty:null, status:'لم يتم جرده'}; }
  async function load(){ ensureSection(); const current=await openAudit(); const box=$('auditLockMsgV10046'); if(box){ box.classList.toggle('hidden',!current); box.textContent=current?`يوجد جرد مفتوح: ${current.audit_no||current.id} - المالية والمخزون مغلق مؤقتًا`:''; } await renderSessions(); if(current) await renderItems(current.id,current); await applyFinanceLock(); }
  async function renderSessions(){ const wrap=$('auditSessionsV10046'); if(!wrap||!window.sb) return; const r=await sb.from('inventory_audit_sessions').select('*').order('id',{ascending:false}).limit(30); const rows=r.data||[]; wrap.innerHTML=rows.map(a=>`<div class="quick-item"><div><b>${a.audit_no||a.id}</b><br><small>${a.title||'جرد'} - ${a.status==='open'?'مفتوح':'مغلق'} - ${new Date(a.started_at).toLocaleString('ar-SA')}</small></div><button class="light" onclick="tasneefInventoryAuditV10046.renderItems(${a.id})">عرض</button></div>`).join('')||'<div class="summary-item">لا توجد عمليات جرد</div>'; }
  async function renderItems(auditId,audit){ const body=$('auditItemsBodyV10046'); if(!body||!window.sb) return; const r=await sb.from('inventory_audit_items').select('*').eq('audit_id',auditId).order('id',{ascending:true}); const rows=r.data||[]; if($('auditTitleV10046')) $('auditTitleV10046').textContent=`تفاصيل الجرد ${audit?.audit_no||auditId}`; body.innerHTML=rows.map(it=>rowHtml(it)).join('')||'<tr><td colspan="9">لا توجد بنود</td></tr>'; }
  function rowHtml(it){ const diff=N(it.actual_qty)-N(it.system_qty); const st=it.actual_qty==null?'لم يتم جرده':diff===0?'مطابق':diff<0?'نقص':'زيادة'; return `<tr data-id="${it.id}"><td>${it.product_name||''}</td><td>${it.product_code||''}</td><td>${it.distributor_code||''}</td><td>${it.unit||''}</td><td>${N(it.system_qty).toFixed(2)}</td><td><input type="number" step="0.01" value="${it.actual_qty??''}" onchange="tasneefInventoryAuditV10046.saveQty(${it.id},this.value)"></td><td>${diff.toFixed(2)}</td><td><span class="badge ${st==='نقص'?'red':st==='زيادة'?'amber':st==='مطابق'?'green':''}">${st}</span></td><td><input value="${it.notes||''}" onchange="tasneefInventoryAuditV10046.saveNote(${it.id},this.value)"></td></tr>`; }
  async function newAudit(){ ensureSection(); if(await openAudit()) return say('يوجد جرد مفتوح بالفعل. أغلقه أولاً.','err'); const title=prompt('اسم عملية الجرد','جرد المخزون')||'جرد المخزون'; const auditNo='AUD-'+new Date().toISOString().slice(0,10).replace(/-/g,'')+'-'+Math.floor(Math.random()*9000+1000); const session=await sb.from('inventory_audit_sessions').insert({audit_no:auditNo,title,status:'open',created_by:JSON.parse(localStorage.getItem('tasneef_user')||'{}')?.username||''}).select('*').single(); if(session.error) return say(session.error.message,'err'); const products=(await getProducts()).map(productRow).filter(x=>x.product_name||x.product_code); const batch=products.map(p=>Object.assign({audit_id:session.data.id},p)); for(let i=0;i<batch.length;i+=500){ const r=await sb.from('inventory_audit_items').insert(batch.slice(i,i+500)); if(r.error) return say(r.error.message,'err'); } say('تم فتح الجرد وقفل المالية والمخزون'); await load(); }
  async function saveQty(id,val){ const actual=val===''?null:N(val); const row={actual_qty:actual,status:actual==null?'لم يتم جرده':''}; if(actual!=null){ const tr=document.querySelector(`tr[data-id="${id}"]`); const sys=N(tr?.children?.[4]?.textContent); row.status=(actual-sys)===0?'مطابق':(actual-sys)<0?'نقص':'زيادة'; } const r=await sb.from('inventory_audit_items').update(row).eq('id',id); if(r.error) say(r.error.message,'err'); await load(); }
  async function saveNote(id,val){ await sb.from('inventory_audit_items').update({notes:S(val)}).eq('id',id); }
  async function closeAudit(){ const a=await openAudit(); if(!a) return say('لا يوجد جرد مفتوح','err'); if(!confirm('إغلاق الجرد؟ سيتم فتح المالية والمخزون بعد الإغلاق.')) return; const r=await sb.from('inventory_audit_sessions').update({status:'closed',closed_at:new Date().toISOString()}).eq('id',a.id); if(r.error) return say(r.error.message,'err'); say('تم إغلاق الجرد وفتح المالية والمخزون'); await load(); }
  async function applyFinanceLock(){ const a=await openAudit(); const fin=$('financeDashboard'); if(!fin) return; let lock=$('financeAuditLockV10046'); if(!a){ lock?.remove(); return; } if(!lock){ lock=document.createElement('div'); lock.id='financeAuditLockV10046'; lock.className='msg err'; lock.style.cssText='position:sticky;top:0;z-index:9999;margin-bottom:12px;font-weight:900'; fin.prepend(lock); } lock.innerHTML=`قسم المالية والمخزون مغلق مؤقتًا للجرد المفتوح: <b>${a.audit_no||a.id}</b> <button class="light" onclick="showPage('inventoryAudit',document.querySelector('[data-page=inventoryAudit]'))">فتح الجرد</button>`; fin.querySelectorAll('button:not(#financeAuditLockV10046 button), input, select, textarea').forEach(el=>{ if(!lock.contains(el)) el.disabled=true; }); }
  function print(){ window.print(); }
  function exportCsv(){ const rows=[...document.querySelectorAll('#auditItemsBodyV10046 tr')].map(tr=>[...tr.children].map(td=>`"${td.innerText.replace(/"/g,'""')}"`).join(',')); const blob=new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv;charset=utf-8'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='inventory-audit.csv'; a.click(); }
  window.tasneefInventoryAuditV10046={load,newAudit,renderItems,saveQty,saveNote,closeAudit,print,exportCsv};
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',()=>setTimeout(load,500)); else setTimeout(load,500);
  window.addEventListener('load',()=>setTimeout(load,1200));
})();
