/* Tasneef CRM Unified V10600 - single canonical CRM module */
(function(){
'use strict';
if(window.__tasneefCrmUnifiedV10600) return; window.__tasneefCrmUnifiedV10600=true;
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const stageMeta={new:['عميل جديد','#2563eb'],contacting:['جاري التواصل','#0ea5e9'],inspected:['تمت المعاينة','#7c3aed'],quote_preparing:['جاري إعداد العرض','#f97316'],quote_sent:['تم إرسال العرض','#eab308'],negotiation:['متابعة وتفاوض','#b7791f'],won:['تم التعاقد','#16a34a'],lost:['لم يتم التعاقد','#dc2626'],handover:['تم التحويل للتشغيل','#0f766e']};
let state={leads:[],tasks:[],activities:[],quotes:[],contracts:[],notifications:[],view:'table',filters:{},selected:null,loading:false};
const sbx=()=>window.sb||window.supabaseClient||null;
function toast(t,err){ if(window.msg) return window.msg(t,err?'err':''); alert(t); }
function uid(){return (crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2));}
function now(){return new Date().toISOString();} function today(){return now().slice(0,10)}
function stageLabel(v){return (stageMeta[v]||[v||'-'])[0]} function stageBadge(v){const m=stageMeta[v]||['-', '#64748b'];return `<span class="crm-stage" style="--sc:${m[1]}">${esc(m[0])}</span>`}
async function q(table,select='*'){const s=sbx();if(!s)return {data:JSON.parse(localStorage.getItem('tasneef_'+table)||'[]')}; const r=await s.from(table).select(select); return r;}
async function insert(table,row){const s=sbx();if(!s){const a=JSON.parse(localStorage.getItem('tasneef_'+table)||'[]');row.id=row.id||uid();a.unshift(row);localStorage.setItem('tasneef_'+table,JSON.stringify(a));return {data:[row]};} return s.from(table).insert(row).select();}
async function update(table,id,row){const s=sbx();if(!s){const a=JSON.parse(localStorage.getItem('tasneef_'+table)||'[]');const i=a.findIndex(x=>String(x.id)===String(id));if(i>=0)a[i]={...a[i],...row};localStorage.setItem('tasneef_'+table,JSON.stringify(a));return {data:[a[i]]};} return s.from(table).update(row).eq('id',id).select();}
async function load(){state.loading=true; renderLoading(); const [l,t,a,qu,c,n]=await Promise.all([q('crm_opportunities'),q('crm_tasks'),q('crm_activities'),q('crm_quotes'),q('crm_contracts'),q('crm_notifications')]); state.leads=l.data||[];state.tasks=t.data||[];state.activities=a.data||[];state.quotes=qu.data||[];state.contracts=c.data||[];state.notifications=n.data||[];state.loading=false;render();}
function stats(){const open=state.leads.filter(x=>!['won','lost','handover'].includes(x.stage));const won=state.leads.filter(x=>['won','handover'].includes(x.stage));return {total:state.leads.length,new:state.leads.filter(x=>x.stage==='new').length,open:open.length,inspect:state.leads.filter(x=>x.stage==='inspected').length,quotes:state.leads.filter(x=>['quote_preparing','quote_sent'].includes(x.stage)).length,nego:state.leads.filter(x=>x.stage==='negotiation').length,won:won.length,lost:state.leads.filter(x=>x.stage==='lost').length,value:open.reduce((s,x)=>s+Number(x.expected_value||0),0),contracts:state.contracts.reduce((s,x)=>s+Number(x.contract_value||0),0),overdue:state.tasks.filter(x=>x.status!=='completed'&&x.due_date&&x.due_date<today()).length,stale:state.leads.filter(x=>{const d=x.last_contact_at||x.created_at;return d&&Date.now()-new Date(d)>3*864e5&&!['won','lost','handover'].includes(x.stage)}).length,rate:state.leads.length?Math.round(won.length/state.leads.length*100):0};}
function renderLoading(){const root=$('crmRootV10600');if(root)root.innerHTML='<div class="crm-skeleton"><i></i><i></i><i></i><i></i></div>'}
function matches(x){const f=state.filters,qv=(f.q||'').trim().toLowerCase();if(qv&&!([x.lead_number,x.customer_name,x.phone,x.email,x.project_name,x.city,x.sales_owner_name].join(' ').toLowerCase().includes(qv)))return false;if(f.stage&&x.stage!==f.stage)return false;if(f.city&&x.city!==f.city)return false;if(f.owner&&String(x.sales_owner_id)!==String(f.owner))return false;return true}
function toolbar(){return `<div class="crm-toolbar"><div><h2>إدارة علاقات العملاء والمبيعات</h2><p>رحلة العميل من أول اهتمام حتى التحويل للتشغيل</p></div><div class="crm-actions"><button onclick="tasneefCRM.openLead()">+ عميل جديد</button><button class="light" onclick="tasneefCRM.openTask()">+ مهمة</button><button class="light" onclick="tasneefCRM.load()">تحديث</button></div></div><div class="crm-filters"><input id="crmSearch" placeholder="بحث بالاسم، الجوال، المشروع أو رقم الفرصة" oninput="tasneefCRM.setFilter('q',this.value)"><select onchange="tasneefCRM.setFilter('stage',this.value)"><option value="">كل المراحل</option>${Object.entries(stageMeta).map(([k,v])=>`<option value="${k}">${v[0]}</option>`).join('')}</select><select onchange="tasneefCRM.changeView(this.value)"><option value="table">عرض جدولي</option><option value="cards">بطاقات</option><option value="kanban">Kanban</option><option value="tasks">المهام</option></select><button class="light" onclick="tasneefCRM.clearFilters()">مسح</button></div>`}
function dashboard(){const s=stats(),cards=[['عملاء جدد',s.new,'new'],['فرص مفتوحة',s.open,'open'],['تمت المعاينة',s.inspect,'inspected'],['العروض',s.quotes,'quote_sent'],['تفاوض',s.nego,'negotiation'],['عقود موقعة',s.won,'won'],['لم يتم التعاقد',s.lost,'lost'],['مهام متأخرة',s.overdue,'tasks']];return `<div class="crm-kpis">${cards.map(c=>`<button class="crm-kpi" onclick="tasneefCRM.kpi('${c[2]}')"><small>${c[0]}</small><b>${c[1]}</b></button>`).join('')}</div><div class="crm-money"><div><small>قيمة الفرص المفتوحة</small><b>${s.value.toLocaleString('ar-SA')} ر.س</b></div><div><small>قيمة العقود</small><b>${s.contracts.toLocaleString('ar-SA')} ر.س</b></div><div><small>نسبة التحويل</small><b>${s.rate}%</b></div><div><small>دون متابعة 3 أيام</small><b>${s.stale}</b></div></div>`}
function filtered(){return state.leads.filter(matches)}
function tableView(){const rows=filtered();return `<div class="table-wrap"><table><thead><tr><th>رقم الفرصة</th><th>العميل / المشروع</th><th>الجوال</th><th>المدينة</th><th>المرحلة</th><th>القيمة</th><th>آخر تواصل</th><th>المتابعة القادمة</th><th>المسؤول</th><th>الإجراءات</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.lead_number||'-')}</td><td><b>${esc(x.customer_name)}</b><br><small>${esc(x.project_name||'')}</small></td><td>${esc(x.phone||'-')}</td><td>${esc(x.city||'-')}</td><td>${stageBadge(x.stage)}</td><td>${Number(x.expected_value||0).toLocaleString('ar-SA')}</td><td>${esc((x.last_contact_at||'').slice(0,10)||'-')}</td><td>${esc((x.next_follow_up_at||'').slice(0,10)||'-')}</td><td>${esc(x.sales_owner_name||'-')}</td><td class="row-actions"><button onclick="tasneefCRM.openProfile('${x.id}')">عرض</button><button class="light" onclick="tasneefCRM.openLead('${x.id}')">تعديل</button></td></tr>`).join('')||'<tr><td colspan="10">لا توجد نتائج</td></tr>'}</tbody></table></div>`}
function cardsView(){const rows=filtered();return `<div class="crm-card-grid">${rows.map(x=>`<article class="crm-lead-card"><div class="crm-card-head">${stageBadge(x.stage)}<b>${esc(x.lead_number||'')}</b></div><h3>${esc(x.customer_name)}</h3><p>${esc(x.project_name||'بدون اسم مشروع')}</p><dl><div><dt>الجوال</dt><dd>${esc(x.phone||'-')}</dd></div><div><dt>القيمة</dt><dd>${Number(x.expected_value||0).toLocaleString('ar-SA')} ر.س</dd></div><div><dt>المتابعة</dt><dd>${esc((x.next_follow_up_at||'').slice(0,10)||'-')}</dd></div></dl><button onclick="tasneefCRM.openProfile('${x.id}')">فتح الملف</button></article>`).join('')||'<div class="crm-empty">لا توجد عملاء مطابقون</div>'}</div>`}
function kanban(){const rows=filtered();return `<div class="crm-kanban">${Object.entries(stageMeta).filter(([k])=>k!=='handover').map(([k,m])=>`<section class="crm-column" ondragover="event.preventDefault()" ondrop="tasneefCRM.drop(event,'${k}')"><header style="border-color:${m[1]}"><b>${m[0]}</b><span>${rows.filter(x=>x.stage===k).length}</span></header>${rows.filter(x=>x.stage===k).map(x=>`<article draggable="true" ondragstart="event.dataTransfer.setData('text/plain','${x.id}')" onclick="tasneefCRM.openProfile('${x.id}')"><b>${esc(x.customer_name)}</b><small>${esc(x.project_name||'')}</small><em>${Number(x.expected_value||0).toLocaleString('ar-SA')} ر.س</em></article>`).join('')}</section>`).join('')}</div>`}
function tasksView(){const rows=state.tasks.slice().sort((a,b)=>String(a.due_date).localeCompare(String(b.due_date)));return `<div class="table-wrap"><table><thead><tr><th>المهمة</th><th>العميل</th><th>المسؤول</th><th>الاستحقاق</th><th>الأولوية</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>${rows.map(t=>`<tr><td>${esc(t.title)}</td><td>${esc(state.leads.find(x=>String(x.id)===String(t.opportunity_id))?.customer_name||'-')}</td><td>${esc(t.assigned_to_name||'-')}</td><td>${esc(t.due_date||'-')} ${esc(t.due_time||'')}</td><td>${esc(t.priority||'عادية')}</td><td>${esc(t.status||'جديدة')}</td><td><button onclick="tasneefCRM.completeTask('${t.id}')">إكمال</button></td></tr>`).join('')||'<tr><td colspan="7">لا توجد مهام</td></tr>'}</tbody></table></div>`}
function render(){const root=$('crmRootV10600');if(!root)return;root.innerHTML=toolbar()+dashboard()+`<div class="card crm-main">${state.view==='kanban'?kanban():state.view==='cards'?cardsView():state.view==='tasks'?tasksView():tableView()}</div><div id="crmDrawerV10600"></div>`}
function drawer(html,title){$('crmDrawerV10600').innerHTML=`<div class="crm-overlay" onclick="if(event.target===this)tasneefCRM.closeDrawer()"><aside class="crm-drawer"><header><div><h3>${esc(title)}</h3><small>يتم حفظ المسودة تلقائيًا على هذا الجهاز</small></div><button class="light" onclick="tasneefCRM.closeDrawer()">✕</button></header>${html}</aside></div>`}
function leadForm(x={}){const services=['النظافة','الصيانة','التشغيل','مكافحة الحشرات','التشجير','المصاعد','الدفاع المدني','إدارة المرافق','الحراسة'];return `<form id="crmLeadForm" onsubmit="tasneefCRM.saveLead(event,'${x.id||''}')"><div class="crm-form-grid"><label>اسم العميل*<input name="customer_name" required value="${esc(x.customer_name||'')}"></label><label>رقم الجوال*<input name="phone" required value="${esc(x.phone||'')}"></label><label>البريد الإلكتروني<input name="email" type="email" value="${esc(x.email||'')}"></label><label>اسم المشروع*<input name="project_name" required value="${esc(x.project_name||'')}"></label><label>المدينة<input name="city" value="${esc(x.city||'الرياض')}"></label><label>الحي<input name="district" value="${esc(x.district||'')}"></label><label>نوع المشروع<select name="project_type">${['مجمع سكني','برج','جمعية ملاك','فندق','مبنى تجاري','مكاتب','مستودع','مدرسة','منشأة صحية','مشروع آخر'].map(v=>`<option ${x.project_type===v?'selected':''}>${v}</option>`).join('')}</select></label><label>عدد الوحدات<input name="units_count" type="number" min="0" value="${esc(x.units_count||'')}"></label><label>مصدر العميل<input name="source_name" value="${esc(x.source_name||'')}"></label><label>مسؤول المبيعات<input name="sales_owner_name" value="${esc(x.sales_owner_name||'')}"></label><label>القيمة المتوقعة<input name="expected_value" type="number" min="0" step="0.01" value="${esc(x.expected_value||'')}"></label><label>الأولوية<select name="priority"><option>عادية</option><option ${x.priority==='عالية'?'selected':''}>عالية</option><option ${x.priority==='عاجلة'?'selected':''}>عاجلة</option></select></label></div><label>الخدمات المطلوبة<div class="crm-checks">${services.map(v=>`<label><input type="checkbox" name="services" value="${v}" ${(x.services||[]).includes(v)?'checked':''}> ${v}</label>`).join('')}</div></label><label>ملاحظات<textarea name="notes">${esc(x.notes||'')}</textarea></label><div class="crm-submit"><button type="submit">حفظ العميل</button></div></form>`}
async function saveLead(e,id){e.preventDefault();const fd=new FormData(e.target),row=Object.fromEntries(fd.entries());row.services=fd.getAll('services');row.units_count=Number(row.units_count||0);row.expected_value=Number(row.expected_value||0);row.updated_at=now();if(!id){const dup=state.leads.find(x=>(row.phone&&x.phone===row.phone)||(row.email&&x.email===row.email)||(row.project_name&&x.project_name===row.project_name));if(dup&&!confirm(`يوجد سجل مشابه: ${dup.customer_name} / ${dup.project_name}\nهل تريد المتابعة وإنشاء سجل جديد؟`))return;row.stage='new';row.lead_number='CRM-'+new Date().getFullYear()+'-'+String(state.leads.length+1).padStart(5,'0');row.created_at=now();const r=await insert('crm_opportunities',row);if(r.error)return toast(r.error.message,true);const lead=r.data?.[0]||row;await insert('crm_stage_history',{opportunity_id:lead.id,from_stage:null,to_stage:'new',changed_at:now(),notes:'إنشاء فرصة جديدة'});await insert('crm_tasks',{opportunity_id:lead.id,title:'التواصل الأولي مع العميل',task_type:'اتصال',due_date:today(),status:'new',priority:'عالية',created_at:now()});}else{const r=await update('crm_opportunities',id,row);if(r.error)return toast(r.error.message,true)}localStorage.removeItem('crmDraftLead');toast('تم حفظ العميل بنجاح');closeDrawer();await load()}
function openLead(id){const x=state.leads.find(v=>String(v.id)===String(id))||{};drawer(leadForm(x),id?'تعديل بيانات العميل':'إضافة عميل جديد');setTimeout(()=>{const f=$('crmLeadForm');f?.addEventListener('input',()=>localStorage.setItem('crmDraftLead',JSON.stringify(Object.fromEntries(new FormData(f).entries()))))},0)}
function profileHtml(x){const acts=state.activities.filter(a=>String(a.opportunity_id)===String(x.id));const tasks=state.tasks.filter(a=>String(a.opportunity_id)===String(x.id));return `<div class="crm-profile-head"><div>${stageBadge(x.stage)}<h2>${esc(x.customer_name)}</h2><p>${esc(x.project_name||'')} — ${esc(x.phone||'')}</p></div><select onchange="tasneefCRM.changeStage('${x.id}',this.value)">${Object.entries(stageMeta).map(([k,v])=>`<option value="${k}" ${x.stage===k?'selected':''}>${v[0]}</option>`).join('')}</select></div><div class="crm-profile-grid"><div><small>القيمة المتوقعة</small><b>${Number(x.expected_value||0).toLocaleString('ar-SA')} ر.س</b></div><div><small>المسؤول</small><b>${esc(x.sales_owner_name||'-')}</b></div><div><small>آخر تواصل</small><b>${esc((x.last_contact_at||'').slice(0,10)||'-')}</b></div><div><small>المتابعة القادمة</small><b>${esc((x.next_follow_up_at||'').slice(0,10)||'-')}</b></div></div><div class="crm-profile-actions"><button onclick="tasneefCRM.activity('${x.id}')">تسجيل تواصل</button><button class="light" onclick="tasneefCRM.openTask('${x.id}')">إنشاء مهمة</button><button class="light" onclick="tasneefCRM.openLead('${x.id}')">تعديل</button>${x.stage==='won'?`<button onclick="tasneefCRM.handover('${x.id}')">تحويل للتشغيل</button>`:''}</div><h3>السجل الزمني</h3><div class="crm-timeline">${acts.map(a=>`<article><b>${esc(a.activity_type)}</b><small>${esc((a.activity_at||a.created_at||'').replace('T',' ').slice(0,16))}</small><p>${esc(a.notes||a.result||'')}</p></article>`).join('')||'<p>لا توجد أنشطة مسجلة</p>'}</div><h3>المهام</h3>${tasks.map(t=>`<div class="crm-task-line"><b>${esc(t.title)}</b><span>${esc(t.due_date||'')}</span><em>${esc(t.status||'جديدة')}</em></div>`).join('')||'<p>لا توجد مهام</p>'}`}
function openProfile(id){const x=state.leads.find(v=>String(v.id)===String(id));if(x)drawer(profileHtml(x),'ملف العميل الذكي')}
async function changeStage(id,to){const x=state.leads.find(v=>String(v.id)===String(id));if(!x||x.stage===to)return;if(to==='won'&&!confirm('تأكيد تحويل الفرصة إلى تم التعاقد؟ يجب استكمال بيانات العقد بعد ذلك.'))return;const from=x.stage;await update('crm_opportunities',id,{stage:to,stage_changed_at:now(),updated_at:now()});await insert('crm_stage_history',{opportunity_id:id,from_stage:from,to_stage:to,changed_at:now(),notes:''});await insert('crm_audit_logs',{entity_type:'opportunity',entity_id:id,action:'stage_change',old_data:{stage:from},new_data:{stage:to},created_at:now()});toast('تم تغيير المرحلة');await load();openProfile(id)}
function activity(id){drawer(`<form onsubmit="tasneefCRM.saveActivity(event,'${id}')"><label>نوع النشاط<select name="activity_type">${['اتصال هاتفي','رسالة واتساب','بريد إلكتروني','اجتماع','زيارة ميدانية','معاينة','إرسال عرض سعر','متابعة عرض','تفاوض','ملاحظة داخلية','توقيع عقد'].map(v=>`<option>${v}</option>`).join('')}</select></label><label>النتيجة*<input name="result" required></label><label>الملاحظات<textarea name="notes"></textarea></label><label>موعد المتابعة القادمة<input name="next_follow_up_at" type="datetime-local"></label><button>حفظ النشاط</button></form>`,'تسجيل تواصل')}
async function saveActivity(e,id){e.preventDefault();const row=Object.fromEntries(new FormData(e.target).entries());row.opportunity_id=id;row.activity_at=now();row.created_at=now();const r=await insert('crm_activities',row);if(r.error)return toast(r.error.message,true);await update('crm_opportunities',id,{last_contact_at:now(),next_follow_up_at:row.next_follow_up_at||null,stage:state.leads.find(x=>String(x.id)===String(id))?.stage==='new'?'contacting':state.leads.find(x=>String(x.id)===String(id))?.stage});toast('تم تسجيل التواصل');closeDrawer();await load()}
function openTask(id=''){drawer(`<form onsubmit="tasneefCRM.saveTask(event)"><label>العميل<select name="opportunity_id" required><option value="">اختر العميل</option>${state.leads.map(x=>`<option value="${x.id}" ${String(x.id)===String(id)?'selected':''}>${esc(x.customer_name)} - ${esc(x.project_name||'')}</option>`).join('')}</select></label><label>عنوان المهمة<input name="title" required></label><div class="crm-form-grid"><label>النوع<select name="task_type"><option>اتصال</option><option>زيارة</option><option>معاينة</option><option>إعداد عرض</option><option>إرسال عرض</option><option>متابعة</option><option>اجتماع</option><option>توقيع عقد</option></select></label><label>تاريخ الاستحقاق<input name="due_date" type="date" required></label><label>الوقت<input name="due_time" type="time"></label><label>الأولوية<select name="priority"><option>عادية</option><option>عالية</option><option>عاجلة</option></select></label></div><label>الوصف<textarea name="description"></textarea></label><button>حفظ المهمة</button></form>`,'إنشاء مهمة')}
async function saveTask(e){e.preventDefault();const row=Object.fromEntries(new FormData(e.target).entries());row.status='new';row.created_at=now();const r=await insert('crm_tasks',row);if(r.error)return toast(r.error.message,true);toast('تم إنشاء المهمة');closeDrawer();await load()}
async function completeTask(id){await update('crm_tasks',id,{status:'completed',completed_at:now()});toast('تم إكمال المهمة');await load()}
async function handover(id){const x=state.leads.find(v=>String(v.id)===String(id));if(!x)return; if(x.operation_project_id)return toast('تم تحويل هذا المشروع مسبقًا',true);if(!confirm(`سيتم إنشاء مشروع تشغيلي باسم ${x.project_name}. متابعة؟`))return;const s=sbx();if(!s)return toast('التحويل التشغيلي يتطلب الاتصال بقاعدة البيانات',true);const project={name:x.project_name,location:[x.city,x.district].filter(Boolean).join(' - '),status:'active',notes:`محول من CRM - العميل: ${x.customer_name} - الجوال: ${x.phone||''}`,contract_start:x.contract_start||null,contract_end:x.contract_end||null};const r=await s.from('projects').insert(project).select().single();if(r.error)return toast(r.error.message,true);await update('crm_opportunities',id,{stage:'handover',operation_project_id:r.data.id,handed_over_at:now()});await insert('crm_operation_handover',{opportunity_id:id,project_id:r.data.id,status:'completed',handover_at:now(),notes:'تم إنشاء المشروع التشغيلي من CRM'});toast('تم تحويل العميل إلى التشغيل وإنشاء المشروع بنجاح');await load();openProfile(id)}
function closeDrawer(){const d=$('crmDrawerV10600');if(d)d.innerHTML=''}
function setFilter(k,v){state.filters[k]=v;render()}function clearFilters(){state.filters={};render()}function changeView(v){state.view=v;render()}function kpi(k){if(k==='tasks'){state.view='tasks';render();return}state.filters.stage=k==='open'?'':k;state.view='table';render()}async function drop(e,stage){const id=e.dataTransfer.getData('text/plain');await changeStage(id,stage)}
window.tasneefCRM={load,render,openLead,saveLead,openProfile,changeStage,activity,saveActivity,openTask,saveTask,completeTask,handover,closeDrawer,setFilter,clearFilters,changeView,kpi,drop};
const oldShow=window.showPage;window.showPage=function(id,btn){if(typeof oldShow==='function')oldShow(id,btn);if(id==='crm')setTimeout(load,40)};
window.addEventListener('load',()=>{if($('crm')&&!$('crmRootV10600'))$('crm').innerHTML='<div id="crmRootV10600"></div>';});
})();
