(function(){
  'use strict';
  if(window.__tasneefSupervisorOrdersV10061) return;
  window.__tasneefSupervisorOrdersV10061 = true;
  const SUPABASE_URL='https://zmjdqiswytxlbfgnfjfv.supabase.co';
  const SUPABASE_ANON_KEY='sb_publishable_ADsAC5MtBCusDgX62c8NaQ_LyyuTPeb';
  const TABLE='orders_shared';
  const HEADERS=['رقم الطلب','رقم الطلب بالجروب','تاريخ الطلب','وقت الطلب','مرسل الطلب','المشروع','نوع العقار','رقم الشقة','اسم العميل','رقم العميل','المنفذ','التفاصيل','ملاحظات','تخص','تاريخ التنفيذ','كيفية التنفيذ','حالة التنفيذ','تقرير','السعر (شامل الضريبة)','الضريبة 15%','السعر قبل الضريبة','التكلفة','الربح','حالة السداد','رقم الفاتورة','فوترة بالسيستم'];
  const $=id=>document.getElementById(id); const S=v=>String(v??'').trim(); const A=v=>Array.isArray(v)?v:[];
  const esc=v=>S(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const N=v=>{ const n=Number(S(v).replace(/[^0-9.\-]/g,'')); return Number.isFinite(n)?n:0; };
  let allRows=[], myRows=[];
  function user(){ try{return JSON.parse(localStorage.getItem('tasneef_user')||'{}')||{};}catch(_){return{};} }
  function userName(){ const u=user(); return S(u.full_name||u.name||u.username||'مشرف'); }
  function username(){ return S(user().username||user().email||userName()); }
  function sb(){ return window.sb || (window.supabase && window.supabase.createClient ? window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY) : null); }
  function today(){ return new Date().toISOString().slice(0,10); }
  function timeNow(){ return new Date().toTimeString().slice(0,5); }
  function normalizeNo(v){ return S(v).replace(/\s+/g,'').toUpperCase(); }
  function orderNo(r){ return normalizeNo(r&& (r['رقم الطلب']||r.order_no||r.orderNo)); }
  function field(r,h){ return r?S(r[h]):''; }
  function orderNum(r){ const m=orderNo(r).match(/(\d+)/g); return m?Number(m[m.length-1])||0:0; }
  function nextNo(){ const max=Math.max(0,...allRows.map(orderNum)); return 'ORD'+String(max+1).padStart(4,'0'); }
  function calc(r){ const inc=N(r['السعر (شامل الضريبة)']); const cost=N(r['التكلفة']); if(inc||cost){ const before=+(inc/1.15).toFixed(2); const vat=+(inc-before).toFixed(2); r['السعر قبل الضريبة']=before; r['الضريبة 15%']=vat; r['الربح']=+(before-cost).toFixed(2); } return r; }
  function own(r){ const u=user(); const vals=[r.created_by_username,r.created_by_name,r.supervisor_username,r.supervisor_name,r['مرسل الطلب'],r.updated_by_name].map(S).map(x=>x.toLowerCase()); const names=[username(),userName(),S(u.full_name),S(u.name),S(u.username)].filter(Boolean).map(x=>x.toLowerCase()); return vals.some(v=>v && names.includes(v)); }
  function options(){
    const projects=new Set();
    A(window.data&&window.data.projects).forEach(p=>{ const n=S(p.name||p.project_name||p.title); if(n) projects.add(n); });
    allRows.forEach(r=>{ const n=S(r['المشروع']); if(n) projects.add(n); });
    const html='<option value="">اختر المشروع</option>'+[...projects].sort().map(p=>`<option value="${esc(p)}">${esc(p)}</option>`).join('');
    ['supOrderProjectV10061'].forEach(id=>{ if($(id)){ const cur=$(id).value; $(id).innerHTML=html; if(cur) $(id).value=cur; }});
    const filter='<option value="">كل المشاريع</option>'+[...projects].sort().map(p=>`<option value="${esc(p)}">${esc(p)}</option>`).join('');
    if($('supOrderFilterProjectV10061')){ const cur=$('supOrderFilterProjectV10061').value; $('supOrderFilterProjectV10061').innerHTML=filter; if(cur) $('supOrderFilterProjectV10061').value=cur; }
  }
  function clear(){ ['supOrderEditNoV10061','supOrderUnitV10061','supOrderClientV10061','supOrderPhoneV10061','supOrderDetailsV10061','supOrderNotesV10061'].forEach(id=>{ if($(id)) $(id).value=''; }); if($('supOrderConcernV10061')) $('supOrderConcernV10061').value='الجمعية'; if($('supOrderStatusV10061')) $('supOrderStatusV10061').value='لم ينفذ'; if($('supOrderFormTitleV10061')) $('supOrderFormTitleV10061').textContent='رفع أوردر جديد'; }
  function formRow(old){ const no=S($('supOrderEditNoV10061')?.value)||orderNo(old)||nextNo(); const r=Object.assign({},old||{}); r['رقم الطلب']=no; r.order_no=no; r.orderNo=no; r['رقم الطلب بالجروب']=r['رقم الطلب بالجروب']||''; r['تاريخ الطلب']=r['تاريخ الطلب']||today(); r['وقت الطلب']=r['وقت الطلب']||timeNow(); r['مرسل الطلب']=userName(); r['المشروع']=S($('supOrderProjectV10061')?.value); r['نوع العقار']=r['نوع العقار']||''; r['رقم الشقة']=S($('supOrderUnitV10061')?.value); r['اسم العميل']=S($('supOrderClientV10061')?.value); r['رقم العميل']=S($('supOrderPhoneV10061')?.value); r['المنفذ']=r['المنفذ']||''; r['التفاصيل']=S($('supOrderDetailsV10061')?.value); r['ملاحظات']=S($('supOrderNotesV10061')?.value); r['تخص']=S($('supOrderConcernV10061')?.value)||'الجمعية'; r['حالة التنفيذ']=S($('supOrderStatusV10061')?.value)||'لم ينفذ'; r['حالة السداد']=r['حالة السداد']||'آجل'; r.created_by_name=r.created_by_name||userName(); r.created_by_username=r.created_by_username||username(); r.created_by_id=r.created_by_id||S(user().id); r.updated_by_name=userName(); r.updated_by_username=username(); r.__tasneef_updated_at=new Date().toISOString(); return calc(r); }
  async function load(){ try{ const client=sb(); if(!client) throw new Error('Supabase غير متصل'); const res=await client.from(TABLE).select('order_no,data,updated_at').order('updated_at',{ascending:false}).limit(10000); if(res.error) throw res.error; allRows=A(res.data).map(x=>Object.assign({},x.data||{}, {order_no:x.order_no||orderNo(x.data), __server_updated_at:x.updated_at||''})); myRows=allRows.filter(own); options(); render(); }catch(e){ console.error(e); if($('supOrdersBodyV10061')) $('supOrdersBodyV10061').innerHTML='<div class="summary-item">تعذر تحميل الأوردرات: '+esc(e.message||e)+'</div>'; } }
  async function save(btn){ try{ const old=allRows.find(r=>orderNo(r)===S($('supOrderEditNoV10061')?.value)); const row=formRow(old); if(!row['المشروع']||!row['التفاصيل']) return alert('المشروع والتفاصيل مطلوبان'); if(btn) btn.disabled=true; const client=sb(); const payload={order_no:orderNo(row), data:row, flow:{}, updated_at:new Date().toISOString(), updated_by:'supervisor_'+username()}; const res=await client.from(TABLE).upsert(payload,{onConflict:'order_no'}).select().maybeSingle(); if(res.error) throw res.error; if(typeof msg==='function') msg('تم حفظ الأوردر'); clear(); await load(); }catch(e){ alert('لم يتم حفظ الأوردر: '+(e.message||e)); } finally{ if(btn) btn.disabled=false; } }
  function edit(no){ const r=myRows.find(x=>orderNo(x)===S(no)); if(!r) return; if($('supOrderEditNoV10061')) $('supOrderEditNoV10061').value=orderNo(r); if($('supOrderProjectV10061')) $('supOrderProjectV10061').value=field(r,'المشروع'); if($('supOrderUnitV10061')) $('supOrderUnitV10061').value=field(r,'رقم الشقة'); if($('supOrderClientV10061')) $('supOrderClientV10061').value=field(r,'اسم العميل'); if($('supOrderPhoneV10061')) $('supOrderPhoneV10061').value=field(r,'رقم العميل'); if($('supOrderConcernV10061')) $('supOrderConcernV10061').value=field(r,'تخص')||'الجمعية'; if($('supOrderStatusV10061')) $('supOrderStatusV10061').value=field(r,'حالة التنفيذ')||'لم ينفذ'; if($('supOrderDetailsV10061')) $('supOrderDetailsV10061').value=field(r,'التفاصيل'); if($('supOrderNotesV10061')) $('supOrderNotesV10061').value=field(r,'ملاحظات'); if($('supOrderFormTitleV10061')) $('supOrderFormTitleV10061').textContent='تعديل أوردر '+orderNo(r); $('supOrders')?.scrollIntoView({behavior:'smooth',block:'start'}); }
  function pass(r){ const p=S($('supOrderFilterProjectV10061')?.value), st=S($('supOrderFilterStatusV10061')?.value), q=S($('supOrderSearchV10061')?.value).toLowerCase(); if(p&&field(r,'المشروع')!==p) return false; if(st&&field(r,'حالة التنفيذ')!==st) return false; if(q){ const hay=[orderNo(r),field(r,'المشروع'),field(r,'اسم العميل'),field(r,'رقم العميل'),field(r,'التفاصيل'),field(r,'حالة التنفيذ')].join(' ').toLowerCase(); if(!hay.includes(q)) return false; } return true; }
  function render(){ const rows=myRows.filter(pass); const total=rows.length, done=rows.filter(r=>/تم التنفيذ/.test(field(r,'حالة التنفيذ'))).length, open=rows.filter(r=>/لم ينفذ|تحت/.test(field(r,'حالة التنفيذ'))).length; if($('supOrdersSummaryV10061')) $('supOrdersSummaryV10061').innerHTML=[['إجمالي أوردراتي',total],['تم التنفيذ',done],['مفتوحة',open]].map(x=>`<div class="summary-card-mini"><small>${x[0]}</small><b>${x[1]}</b></div>`).join(''); const box=$('supOrdersBodyV10061'); if(!box) return; box.innerHTML=rows.map(r=>`<div class="quick-item"><div><b>${esc(orderNo(r)||'-')}</b><br><small>${esc(field(r,'المشروع')||'-')} - ${esc(field(r,'حالة التنفيذ')||'-')} - ${esc(field(r,'تاريخ الطلب')||'-')}</small><div style="margin-top:6px;line-height:1.7">${esc(field(r,'التفاصيل')||'-')}</div></div><div class="row-actions"><button class="light" onclick="supOrdersShowV10061('${esc(orderNo(r))}')">عرض</button><button onclick="supOrdersEditV10061('${esc(orderNo(r))}')">تعديل</button><button class="light" onclick="supOrdersWhatsV10061('${esc(orderNo(r))}')">واتساب</button></div></div>`).join('')||'<div class="summary-item">لا توجد أوردرات لك حتى الآن</div>'; }
  function show(no){ const r=myRows.find(x=>orderNo(x)===S(no)); if(!r) return; const body=['رقم الطلب','تاريخ الطلب','مرسل الطلب','المشروع','رقم الشقة','اسم العميل','رقم العميل','تخص','حالة التنفيذ','التفاصيل','ملاحظات'].map(h=>`<div><small>${esc(h)}</small><strong>${esc(field(r,h)||orderNo(r)||'-')}</strong></div>`).join(''); document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" onclick="if(event.target===this)this.remove()" style="position:fixed;inset:0;background:rgba(0,35,28,.45);z-index:999999;display:grid;place-items:center;padding:18px"><div class="card" style="width:min(760px,96vw);max-height:92vh;overflow:auto"><div class="actions" style="justify-content:space-between"><h2>عرض الأوردر: ${esc(orderNo(r))}</h2><button class="danger" onclick="this.closest('.modal-backdrop').remove()">إغلاق</button></div><div class="summary-grid" style="grid-template-columns:repeat(auto-fit,minmax(180px,1fr))">${body}</div></div></div>`); }
  function whats(no){ const r=myRows.find(x=>orderNo(x)===S(no)); if(!r) return; const text=['أوردر صيانة','رقم الطلب: '+orderNo(r),'المشروع: '+field(r,'المشروع'),'العميل: '+field(r,'اسم العميل'),'الجوال: '+field(r,'رقم العميل'),'التفاصيل: '+field(r,'التفاصيل'),'الحالة: '+field(r,'حالة التنفيذ')].join('\n'); window.open('https://wa.me/?text='+encodeURIComponent(text),'_blank'); }
  window.supOrdersLoadV10061=load; window.supOrdersSaveV10061=save; window.supOrdersClearV10061=clear; window.supOrdersRenderV10061=render; window.supOrdersEditV10061=edit; window.supOrdersShowV10061=show; window.supOrdersWhatsV10061=whats;
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',()=>setTimeout(load,1000)); else setTimeout(load,1000);
})();
