/* TASNEEF v288 Orders Department Windows Hotfix */
(function(){
  if(window.__tasneefV288OrdersWindows) return;
  window.__tasneefV288OrdersWindows = true;
  const VERSION='v288-orders-department-windows';
  const ORDER_TABLE='professional_orders';
  const LOG_TABLE='professional_order_logs';
  let ordersCache=[];
  let logsCache=[];
  let legacyCache=[];
  let activeWindow='operations';
  let selectedOrderId=null;

  const statusMap={
    new_operations:'جديد من التشغيل', returned_to_operations:'معاد للتشغيل', sent_finance:'مرسل للمالية', returned_from_finance:'معاد من المالية', finance_approved:'معتمد ماليًا', final_pending:'بانتظار المدير', final_approved:'معتمد نهائيًا', in_execution:'قيد التنفيذ', executed:'تم التنفيذ', closed:'مغلق', rejected:'مرفوض'
  };
  const stageMap={operations:'التشغيل', finance:'المالية', general:'مدير النظام', execution:'التنفيذ', closed:'مغلق', legacy:'الأوردرات القديمة'};
  const winStatuses={
    operations:['new_operations','returned_to_operations','returned_from_finance'],
    finance:['sent_finance'],
    general:['finance_approved','final_pending'],
    execution:['final_approved','in_execution','executed'],
    closed:['closed','rejected']
  };
  const windowButtons=[
    ['operations','نافذة التشغيل'],['finance','نافذة المالية'],['general','نافذة مدير النظام'],['execution','نافذة التنفيذ'],['closed','نافذة المغلق / المرفوض'],['legacy','الأوردرات القديمة']
  ];
  const priorityClass={عاجل:'red', مهم:'amber', عادي:'green'};
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const num=v=>{const n=Number(String(v??0).replace(/,/g,''));return Number.isFinite(n)?n:0;};
  const money=v=>num(v).toLocaleString('ar-SA',{minimumFractionDigits:2,maximumFractionDigits:2});
  const nowISO=()=>new Date().toISOString();
  const toast=(t,bad)=>{try{ if(typeof msg==='function') msg(t,bad?'err':''); else alert(t);}catch(e){alert(t);}};
  const user=()=>{try{return (typeof session==='function'&&session())||JSON.parse(localStorage.getItem('tasneef_user')||'null')||{};}catch(e){return {};}};
  const role=()=>user().role||'admin';
  const userName=()=>user().full_name||user().username||'مستخدم';
  const projects=()=>window.data&&Array.isArray(window.data.projects)?window.data.projects:[];
  const projectName=id=>{const p=projects().find(x=>String(x.id)===String(id));return p?.name||'';};
  const isSupervisor=()=>role()==='supervisor';
  const canOperate=()=>['admin','operations_manager','general_manager'].includes(role());
  const canFinance=()=>['admin','financial_manager','general_manager'].includes(role());
  const canGeneral=()=>['admin','general_manager'].includes(role());
  const canDelete=()=>['admin','general_manager'].includes(role());
  function roleAllowedWindows(){
    const r=role();
    if(r==='financial_manager') return ['finance','legacy'];
    if(r==='general_manager') return ['general','closed','legacy'];
    if(r==='supervisor') return ['operations','execution'];
    return ['operations','finance','general','execution','closed','legacy'];
  }
  function ensureAllowedWindow(){ const allowed=roleAllowedWindows(); if(!allowed.includes(activeWindow)) activeWindow=allowed[0]||'operations'; }

  function ensureBadge(){
    let b=$('tasneefV288Badge');
    if(!b){b=document.createElement('div');b.id='tasneefV288Badge';b.style.cssText='position:fixed;left:10px;bottom:82px;z-index:100000;background:#0A4033;color:#fff;padding:7px 10px;border-radius:999px;font:12px Tahoma;box-shadow:0 4px 16px rgba(0,0,0,.18)';document.body.appendChild(b);} b.textContent='Tasneef '+VERSION;
  }
  function ensureStyle(){
    if($('ordersStyleV288')) return;
    const st=document.createElement('style');st.id='ordersStyleV288';st.textContent=`
      .orders-v288{display:grid;gap:14px}.orders-v288-head{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap}.orders-v288-layout{display:grid;grid-template-columns:420px 1fr;gap:16px;align-items:start}.orders-v288-form{position:sticky;top:10px;max-height:86vh;overflow:auto}.orders-v288-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.orders-v288-grid .wide{grid-column:1/-1}.orders-v288-tabs{display:flex;gap:8px;flex-wrap:wrap;background:#fff;border:1px solid var(--line,#dce6e2);border-radius:18px;padding:10px}.orders-v288-tabs button{background:#eef6f3;color:#0A4033;border:1px solid #dce6e2}.orders-v288-tabs button.active{background:#0A4033;color:#fff}.orders-v288-kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.orders-v288-filters{display:grid;grid-template-columns:2fr repeat(4,1fr);gap:8px;align-items:end;background:#fff;border:1px solid var(--line,#dce6e2);border-radius:18px;padding:10px;margin-bottom:10px}.window-title-v288{font-size:22px;font-weight:900;color:#0A4033}.window-note-v288{color:#60706a;margin-top:4px}.order-log-box-v288{max-height:230px;overflow:auto;border:1px solid var(--line,#dce6e2);border-radius:14px;background:#fbfdfc;padding:8px;margin-top:8px}.order-log-item-v288{border-bottom:1px solid #e8efec;padding:7px 4px;line-height:1.7}.order-log-item-v288:last-child{border-bottom:0}.order-actions-v288{display:flex;gap:6px;flex-wrap:wrap}.orders-v288-table td{white-space:normal;min-width:120px}.orders-v288-table td.desc{min-width:260px}.orders-v288-table .row-actions{min-width:240px}.legacy-chip-v288{background:#f8f5e9;color:#775b00;border-radius:999px;padding:3px 8px;font-weight:900;font-size:12px}.stage-chip-v288{background:#eaf5f0;color:#0A4033;border-radius:999px;padding:4px 9px;font-weight:900;font-size:12px}@media(max-width:1100px){.orders-v288-layout,.orders-v288-kpis,.orders-v288-filters{grid-template-columns:1fr}.orders-v288-form{position:static}.orders-v288-grid{grid-template-columns:1fr}}`;
    document.head.appendChild(st);
  }
  function buildLegacy(){
    const seed=(window.TASNEEF_ORDERS_SEED&&Array.isArray(window.TASNEEF_ORDERS_SEED.orders))?window.TASNEEF_ORDERS_SEED.orders:[];
    legacyCache=seed.map((r,i)=>({
      legacy:true, id:'legacy_'+(r['رقم الطلب']||i), order_no:r['رقم الطلب']||'', group_no:r['رقم الطلب بالجروب']||'', project_name:r['المشروع']||'', title:r['التفاصيل']||'', description:r['ملاحظات']||'', order_type:r['تخص']||'', priority:'عادي', status:(r['حالة التنفيذ']==='تم التنفيذ'?'closed':'new_operations'), current_stage:'legacy', estimated_amount:r['السعر (شامل الضريبة)']||0, approved_amount:r['السعر (شامل الضريبة)']||0, requester_name:r['مرسل الطلب']||'', assigned_to:r['المنفذ']||'', created_at:parseLegacyDate(r['تاريخ الطلب']), payment_method:r['حالة السداد']||'', invoice_no:r['رقم الفاتورة']||'', raw:r
    }));
    try{
      const local=JSON.parse(localStorage.getItem('tasneef_orders')||localStorage.getItem('orders')||'[]');
      if(Array.isArray(local)) local.forEach((r,i)=>legacyCache.unshift({legacy:true,id:'local_'+i,order_no:r.order_no||r['رقم الطلب']||r.id||'',group_no:r.group_no||r['رقم الطلب بالجروب']||'',project_name:r.project_name||r.project||r['المشروع']||'',title:r.title||r.details||r['التفاصيل']||'',description:r.description||r.notes||r['ملاحظات']||'',order_type:r.order_type||r['تخص']||'',priority:r.priority||'عادي',status:r.status||'new_operations',current_stage:'legacy',estimated_amount:r.amount||r.total||r['السعر (شامل الضريبة)']||0,approved_amount:r.approved_amount||r.amount||r['السعر (شامل الضريبة)']||0,requester_name:r.requester_name||r['مرسل الطلب']||'',assigned_to:r.assigned_to||r['المنفذ']||'',created_at:r.created_at||parseLegacyDate(r['تاريخ الطلب']),payment_method:r.payment_method||r['حالة السداد']||'',invoice_no:r.invoice_no||r['رقم الفاتورة']||'',raw:r}));
    }catch(e){}
  }
  function parseLegacyDate(v){
    const s=String(v||'').trim(); if(!s) return '';
    const m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/); if(m){ const d=m[1].padStart(2,'0'), mo=m[2].padStart(2,'0'), y=m[3]; return `${y}-${mo}-${d}`; }
    return s;
  }
  function fillProjectSelect(selId){
    const sel=$(selId); if(!sel) return; let arr=projects(); const u=user();
    if(u.role==='supervisor') arr=arr.filter(p=>String(p.supervisor_id)===String(u.id)||String(p.app_supervisor_id)===String(u.id));
    sel.innerHTML='<option value="">اختر المشروع</option>'+arr.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');
  }
  function fillProjectFilter(){
    const sel=$('opProjectFilterV288'); if(!sel) return;
    sel.innerHTML='<option value="">كل المشاريع داخل هذه النافذة</option>'+projects().map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');
  }
  function orderFormHtml(prefix='op'){
    return `<input type="hidden" id="${prefix}OrderIdV288"><div class="orders-v288-grid">
      <div><label>رقم النظام</label><input id="${prefix}OrderNoV288" readonly placeholder="تلقائي"></div><div><label>رقم القروب</label><input id="${prefix}GroupNoV288" placeholder="رقم الأوردر في القروب"></div>
      <div><label>المشروع</label><select id="${prefix}ProjectV288"></select></div><div><label>نوع الأوردر</label><select id="${prefix}TypeV288"><option>مصروف تشغيلي</option><option>مواد</option><option>صيانة</option><option>مشتريات</option><option>خدمة خارجية</option><option>طارئ</option></select></div>
      <div><label>الأولوية</label><select id="${prefix}PriorityV288"><option>عادي</option><option>مهم</option><option>عاجل</option></select></div><div><label>الكمية</label><input id="${prefix}QtyV288" type="number" step="0.01" value="1"></div>
      <div class="wide"><label>عنوان مختصر</label><input id="${prefix}TitleV288" placeholder="مثال: شراء لمبات للبيسمنت"></div><div class="wide"><label>وصف الطلب</label><textarea id="${prefix}DescV288" placeholder="اكتب تفاصيل الطلب والسبب"></textarea></div>
      <div><label>المبلغ المتوقع</label><input id="${prefix}EstimatedV288" type="number" step="0.01" placeholder="اختياري"></div><div><label>المسؤول / المنفذ</label><input id="${prefix}AssignedV288" placeholder="اختياري"></div>
    </div><div class="actions"><button type="button" onclick="saveProfessionalOrderV288('${prefix}')">حفظ الأوردر</button><button type="button" class="light" onclick="clearProfessionalOrderFormV288('${prefix}')">جديد</button></div>`;
  }
  function financeBox(){ return `<div id="opFinanceBoxV288" class="hidden"><hr><h3>بيانات المالية</h3><div class="orders-v288-grid"><div><label>المبلغ المعتمد</label><input id="opApprovedV288" type="number" step="0.01"></div><div><label>طريقة الدفع</label><select id="opPaymentV288"><option value="">اختر</option><option>نقدي</option><option>تحويل</option><option>عهدة</option><option>فاتورة آجلة</option></select></div><div><label>المورد</label><input id="opSupplierV288"></div><div><label>رقم الفاتورة</label><input id="opInvoiceV288"></div><div class="wide"><label>ملاحظات المالية</label><textarea id="opFinanceNotesV288"></textarea></div></div><div class="actions"><button onclick="financeApproveOrderV288()">اعتماد مالي وإرسال للمدير</button><button class="light" onclick="returnOrderV288('operations')">إرجاع للتشغيل</button></div></div>`; }
  function tabsHtml(){ ensureAllowedWindow(); const allowed=roleAllowedWindows(); return `<div class="orders-v288-tabs">${windowButtons.filter(([k])=>allowed.includes(k)).map(([k,t])=>`<button type="button" class="${activeWindow===k?'active':''}" onclick="setOrdersWindowV288('${k}')">${t} <b id="tabCount_${k}_v288"></b></button>`).join('')}</div>`; }
  function adminHtml(){
    ensureAllowedWindow();
    return `<div class="orders-v288"><div class="card orders-v288-head"><div><h2>إدارة الأوردرات</h2><p class="muted">نفس آلية الأوردرات، لكن كل قسم له نافذة مستقلة ولا تظهر بيانات الأقسام الأخرى.</p></div><div class="actions"><button onclick="loadProfessionalOrdersV288()">تحديث</button><button class="light" onclick="exportProfessionalOrdersV288()">تنزيل Excel</button></div></div>${tabsHtml()}<div class="orders-v288-kpis"><div class="kpi"><small>هذه النافذة</small><b id="opKpiWindowV288">0</b></div><div class="kpi"><small>عاجل</small><b id="opKpiUrgentV288">0</b></div><div class="kpi"><small>مهم</small><b id="opKpiImportantV288">0</b></div><div class="kpi"><small>إجمالي المبالغ</small><b id="opKpiAmountV288">0</b></div><div class="kpi"><small>آخر تحديث</small><b id="opKpiUpdatedV288" style="font-size:15px">-</b></div></div><div class="orders-v288-layout"><div class="card orders-v288-form" id="opFormCardV288"><h2 id="opFormTitleV288">إنشاء أوردر</h2>${orderFormHtml('op')}${financeBox()}<div id="opLogBoxV288" class="order-log-box-v288 hidden"></div></div><div class="card"><div><div class="window-title-v288" id="opWindowTitleV288"></div><div class="window-note-v288" id="opWindowNoteV288"></div></div><div class="orders-v288-filters"><input id="opSearchV288" placeholder="بحث داخل هذه النافذة فقط" oninput="renderProfessionalOrdersV288()"><select id="opProjectFilterV288" onchange="renderProfessionalOrdersV288()"><option value="">كل المشاريع داخل هذه النافذة</option></select><select id="opPriorityFilterV288" onchange="renderProfessionalOrdersV288()"><option value="">كل الأولويات</option><option>عاجل</option><option>مهم</option><option>عادي</option></select><input type="date" id="opFromV288" onchange="renderProfessionalOrdersV288()"><input type="date" id="opToV288" onchange="renderProfessionalOrdersV288()"></div><div class="table-wrap"><table class="orders-v288-table"><thead id="opOrdersHeadV288"></thead><tbody id="opOrdersBodyV288"></tbody></table></div></div></div></div>`;
  }
  function supervisorHtml(){ return `<section class="card"><h2>إنشاء أوردر</h2><div class="sup-help">سيظهر الأوردر في نافذة التشغيل لدى الإدارة، ولن يظهر للمالية إلا بعد إرساله لها.</div>${orderFormHtml('sup')}</section><section class="card"><div class="orders-v288-head"><h2>أوردراتي</h2><button class="light" onclick="loadProfessionalOrdersV288()">تحديث</button></div><div class="table-wrap"><table class="orders-v288-table"><thead id="opOrdersHeadV288"></thead><tbody id="opOrdersBodyV288"></tbody></table></div></section>`; }
  function injectAdmin(){ const sec=$('orders'); if(!sec) return; sec.dataset.v288='1'; sec.innerHTML=adminHtml(); fillProjectSelect('opProjectV288'); fillProjectFilter(); loadProfessionalOrdersV288(); }
  function injectSupervisor(){ const shell=document.querySelector('.mobile-shell'); if(!shell||$('supOrders')) return; const nav=document.querySelector('.sup-tabs'); if(nav){const btn=document.createElement('button');btn.className='sup-tab';btn.type='button';btn.textContent='الأوردرات';btn.onclick=function(){showSupervisorWindow('supOrders',this);setTimeout(loadProfessionalOrdersV288,50);};nav.appendChild(btn);} const sec=document.createElement('section');sec.id='supOrders';sec.className='sup-page';sec.innerHTML=supervisorHtml();const summary=$('supSummary');if(summary)summary.parentNode.insertBefore(sec,summary);else shell.appendChild(sec);fillProjectSelect('supProjectV288');loadProfessionalOrdersV288(); }

  async function nextOrderNo(){ const y=new Date().getFullYear(); const prefix=`ORD-${y}-`; let max=0; try{ const {data,error}=await window.sb.from(ORDER_TABLE).select('order_no').like('order_no',prefix+'%').limit(1000); if(!error&&data)data.forEach(r=>{const n=Number(String(r.order_no||'').split('-').pop()); if(Number.isFinite(n)) max=Math.max(max,n);}); }catch(e){} return prefix+String(max+1).padStart(4,'0'); }
  async function addLog(orderId,action,fromStatus,toStatus,note){ if(!orderId||!window.sb) return; const u=user(); await window.sb.from(LOG_TABLE).insert({order_id:orderId,action,from_status:fromStatus||'',to_status:toStatus||'',user_id:u.id||null,user_name:userName(),user_role:role(),note:note||''}); }
  async function loadProfessionalOrdersV288(){
    ensureBadge();ensureStyle();buildLegacy();
    if(!window.sb){toast('اتصال Supabase غير جاهز',true);return;}
    try{ let q=window.sb.from(ORDER_TABLE).select('*').order('created_at',{ascending:false}).limit(800); const u=user(); if(u.role==='supervisor') q=q.eq('requester_id',u.id); const {data,error}=await q; if(error) throw error; ordersCache=data||[]; const ids=ordersCache.map(o=>o.id).filter(Boolean); logsCache=[]; if(ids.length){const lr=await window.sb.from(LOG_TABLE).select('*').in('order_id',ids).order('created_at',{ascending:false}).limit(1500); if(!lr.error) logsCache=lr.data||[];} renderProfessionalOrdersV288(); }
    catch(e){toast('خطأ الأوردرات: '+(e.message||e),true); const body=$('opOrdersBodyV288'); if(body) body.innerHTML=`<tr><td colspan="10">${esc(e.message||e)}<br>تأكد من تشغيل SQL الخاص بـ v286.</td></tr>`;}
  }
  window.loadProfessionalOrdersV288=loadProfessionalOrdersV288;
  function readForm(prefix){ const projectId=$(prefix+'ProjectV288')?.value||''; const pName=projectName(projectId)||($(prefix+'ProjectV288')?.selectedOptions?.[0]?.textContent||''); return {project_id:projectId?Number(projectId):null,project_name:pName||'',group_no:$(prefix+'GroupNoV288')?.value||'',order_type:$(prefix+'TypeV288')?.value||'مصروف تشغيلي',priority:$(prefix+'PriorityV288')?.value||'عادي',title:$(prefix+'TitleV288')?.value||'',description:$(prefix+'DescV288')?.value||'',quantity:num($(prefix+'QtyV288')?.value||1),estimated_amount:num($(prefix+'EstimatedV288')?.value),assigned_to:$(prefix+'AssignedV288')?.value||''}; }
  async function saveProfessionalOrderV288(prefix){ if(!window.sb) return toast('اتصال Supabase غير جاهز',true); const id=$(prefix+'OrderIdV288')?.value; const row=readForm(prefix); if(!row.project_id) return toast('اختر المشروع',true); if(!row.title&&!row.description) return toast('اكتب عنوان أو وصف الأوردر',true); const u=user(); try{ if(id){ const old=ordersCache.find(o=>String(o.id)===String(id)); const {error}=await window.sb.from(ORDER_TABLE).update(row).eq('id',id); if(error) throw error; await addLog(id,'تعديل الأوردر',old?.status,old?.status,'تم تعديل بيانات الأوردر'); toast('تم تحديث الأوردر'); } else { row.order_no=await nextOrderNo(); row.requester_id=u.id||null; row.requester_name=userName(); row.requester_role=role(); row.status='new_operations'; row.current_stage='operations'; const {data,error}=await window.sb.from(ORDER_TABLE).insert(row).select('*').single(); if(error) throw error; await addLog(data.id,'إنشاء أوردر','',row.status,'تم إنشاء الأوردر من '+userName()); activeWindow='operations'; toast('تم إنشاء الأوردر في نافذة التشغيل'); } clearProfessionalOrderFormV288(prefix); await loadProfessionalOrdersV288(); }catch(e){toast(e.message||String(e),true);} }
  window.saveProfessionalOrderV288=saveProfessionalOrderV288;
  function clearProfessionalOrderFormV288(prefix){ [prefix+'OrderIdV288',prefix+'OrderNoV288',prefix+'GroupNoV288',prefix+'TitleV288',prefix+'DescV288',prefix+'EstimatedV288',prefix+'AssignedV288'].forEach(id=>{if($(id))$(id).value='';}); if($(prefix+'QtyV288'))$(prefix+'QtyV288').value='1'; if($(prefix+'PriorityV288'))$(prefix+'PriorityV288').value='عادي'; if($(prefix+'TypeV288'))$(prefix+'TypeV288').value='مصروف تشغيلي'; if($('opFormTitleV288'))$('opFormTitleV288').textContent='إنشاء أوردر'; selectedOrderId=null; renderLogsBox(null); if($('opFinanceBoxV288'))$('opFinanceBoxV288').classList.add('hidden'); }
  window.clearProfessionalOrderFormV288=clearProfessionalOrderFormV288;
  function editProfessionalOrderV288(id){ const o=ordersCache.find(x=>String(x.id)===String(id)); if(!o) return; selectedOrderId=o.id; const prefix=$('opProjectV288')?'op':'sup'; $(prefix+'OrderIdV288').value=o.id; $(prefix+'OrderNoV288').value=o.order_no||''; $(prefix+'GroupNoV288').value=o.group_no||''; $(prefix+'ProjectV288').value=o.project_id||''; $(prefix+'TypeV288').value=o.order_type||'مصروف تشغيلي'; $(prefix+'PriorityV288').value=o.priority||'عادي'; $(prefix+'QtyV288').value=o.quantity||1; $(prefix+'TitleV288').value=o.title||''; $(prefix+'DescV288').value=o.description||''; $(prefix+'EstimatedV288').value=o.estimated_amount||''; $(prefix+'AssignedV288').value=o.assigned_to||''; if($('opApprovedV288'))$('opApprovedV288').value=o.approved_amount||''; if($('opPaymentV288'))$('opPaymentV288').value=o.payment_method||''; if($('opSupplierV288'))$('opSupplierV288').value=o.supplier_name||''; if($('opInvoiceV288'))$('opInvoiceV288').value=o.invoice_no||''; if($('opFinanceNotesV288'))$('opFinanceNotesV288').value=o.finance_notes||''; if($('opFormTitleV288'))$('opFormTitleV288').textContent='تعديل '+(o.order_no||''); renderLogsBox(o.id); $('orders')?.scrollIntoView({behavior:'smooth',block:'start'}); }
  window.editProfessionalOrderV288=editProfessionalOrderV288;
  function stageForStatus(toStatus){ if(['sent_finance'].includes(toStatus)) return 'finance'; if(['finance_approved','final_pending'].includes(toStatus)) return 'general'; if(['final_approved','in_execution','executed'].includes(toStatus)) return 'execution'; if(['closed','rejected'].includes(toStatus)) return 'closed'; return 'operations'; }
  async function updateStatus(id,toStatus,action,note,patch={}){ const o=ordersCache.find(x=>String(x.id)===String(id)); if(!o) return; const row=Object.assign({status:toStatus,current_stage:stageForStatus(toStatus)},patch); if(toStatus==='sent_finance')row.sent_finance_at=nowISO(); if(toStatus==='finance_approved')row.finance_approved_at=nowISO(); if(toStatus==='final_approved')row.final_approved_at=nowISO(); if(toStatus==='executed')row.executed_at=nowISO(); if(toStatus==='closed')row.closed_at=nowISO(); const {error}=await window.sb.from(ORDER_TABLE).update(row).eq('id',id); if(error) return toast(error.message,true); await addLog(id,action,o.status,toStatus,note||''); activeWindow=row.current_stage; toast('تم نقل الأوردر إلى نافذة '+stageMap[row.current_stage]); await loadProfessionalOrdersV288(); }
  window.sendOrderToFinanceV288=id=>updateStatus(id,'sent_finance','إرسال للمالية','تمت مراجعة التشغيل وإرسال الأوردر للمالية');
  window.finalApproveOrderV288=id=>updateStatus(id,'final_approved','اعتماد نهائي','تم الاعتماد النهائي ونقل الأوردر للتنفيذ');
  window.markOrderExecutionV288=async id=>{const note=prompt('اكتب ملاحظة التنفيذ أو اسم المنفذ:')||''; await updateStatus(id,'executed','تنفيذ الأوردر',note,{execution_notes:note});};
  window.closeOrderV288=id=>updateStatus(id,'closed','إغلاق الأوردر','تم إغلاق الأوردر');
  window.rejectOrderV288=async id=>{const note=prompt('سبب الرفض:')||''; if(!note)return; await updateStatus(id,'rejected','رفض الأوردر',note,{rejection_reason:note});};
  window.returnOrderV288=async target=>{ if(!selectedOrderId)return toast('اختر أوردر أولاً',true); const note=prompt('سبب الإرجاع:')||''; if(!note)return; await updateStatus(selectedOrderId,target==='operations'?'returned_to_operations':'sent_finance',target==='operations'?'إرجاع للتشغيل':'إرجاع للمالية',note); };
  window.financeApproveOrderV288=async function(){ if(!selectedOrderId)return toast('اختر أوردر أولاً',true); const patch={approved_amount:num($('opApprovedV288')?.value),payment_method:$('opPaymentV288')?.value||'',supplier_name:$('opSupplierV288')?.value||'',invoice_no:$('opInvoiceV288')?.value||'',finance_notes:$('opFinanceNotesV288')?.value||''}; await updateStatus(selectedOrderId,'finance_approved','اعتماد مالي','تم اعتماد الأوردر ماليًا وإرساله لمدير النظام',patch); };
  window.deleteProfessionalOrderV288=async id=>{ if(!canDelete())return toast('الحذف للمدير فقط',true); if(!confirm('حذف الأوردر نهائيًا؟'))return; const {error}=await window.sb.from(ORDER_TABLE).delete().eq('id',id); if(error)return toast(error.message,true); toast('تم الحذف'); await loadProfessionalOrdersV288(); };
  function actions(o){ if(o.legacy) return '<span class="legacy-chip-v288">قديم / عرض فقط</span>'; const a=[]; a.push(`<button onclick="editProfessionalOrderV288(${o.id})">عرض/تعديل</button>`); if(canOperate()&&['new_operations','returned_to_operations','returned_from_finance'].includes(o.status))a.push(`<button class="light" onclick="sendOrderToFinanceV288(${o.id})">إرسال للمالية</button>`); if(canFinance()&&o.status==='sent_finance')a.push(`<button class="light" onclick="editProfessionalOrderV288(${o.id});document.getElementById('opFinanceBoxV288')?.classList.remove('hidden')">اعتماد مالي</button>`); if(canGeneral()&&['finance_approved','final_pending'].includes(o.status))a.push(`<button class="light" onclick="finalApproveOrderV288(${o.id})">اعتماد نهائي</button>`); if((canOperate()||isSupervisor())&&['final_approved','in_execution'].includes(o.status))a.push(`<button class="light" onclick="markOrderExecutionV288(${o.id})">تم التنفيذ</button>`); if(canGeneral()&&o.status==='executed')a.push(`<button class="light" onclick="closeOrderV288(${o.id})">إغلاق</button>`); if((canOperate()||canGeneral())&&!['closed','rejected'].includes(o.status))a.push(`<button class="danger" onclick="rejectOrderV288(${o.id})">رفض</button>`); if(canDelete())a.push(`<button class="danger" onclick="deleteProfessionalOrderV288(${o.id})">حذف</button>`); return `<div class="order-actions-v288">${a.join('')}</div>`; }
  function baseRowsForWindow(){ ensureAllowedWindow(); if(activeWindow==='legacy') return legacyCache; return ordersCache.filter(o=>winStatuses[activeWindow].includes(o.status)); }
  function filtered(){ let arr=baseRowsForWindow(); const q=($('opSearchV288')?.value||'').toLowerCase().trim(); const pr=$('opProjectFilterV288')?.value||''; const pri=$('opPriorityFilterV288')?.value||''; const from=$('opFromV288')?.value||''; const to=$('opToV288')?.value||''; if(pr)arr=arr.filter(o=>String(o.project_id)===String(pr)||String(o.project_name||'')===String(projectName(pr))); if(pri)arr=arr.filter(o=>o.priority===pri); if(from)arr=arr.filter(o=>String(o.created_at||'').slice(0,10)>=from); if(to)arr=arr.filter(o=>String(o.created_at||'').slice(0,10)<=to); if(q)arr=arr.filter(o=>[o.order_no,o.group_no,o.project_name,o.title,o.description,o.requester_name,o.assigned_to,o.supplier_name,o.invoice_no,o.payment_method].join(' ').toLowerCase().includes(q)); return arr; }
  function updateCounts(){ const counts={operations:0,finance:0,general:0,execution:0,closed:0,legacy:legacyCache.length}; ordersCache.forEach(o=>{ Object.keys(winStatuses).forEach(k=>{ if(winStatuses[k].includes(o.status)) counts[k]++; }); }); Object.keys(counts).forEach(k=>{const el=$('tabCount_'+k+'_v288'); if(el) el.textContent='('+counts[k]+')';}); }
  function windowNote(){ const notes={operations:'تظهر هنا طلبات التشغيل فقط: الجديد والمعاد للتشغيل. لا تظهر طلبات المالية أو المدير.',finance:'تظهر هنا الطلبات المرسلة للمالية فقط، وبعد الاعتماد تختفي من هذه النافذة وتنتقل للمدير.',general:'تظهر هنا الطلبات المعتمدة ماليًا فقط بانتظار اعتماد مدير النظام.',execution:'تظهر هنا الطلبات المعتمدة نهائيًا والمطلوب تنفيذها أو إغلاقها بعد التنفيذ.',closed:'تظهر هنا الأوردرات المغلقة أو المرفوضة فقط.',legacy:'هنا تظهر الأوردرات القديمة من النسخة السابقة للرجوع لها، وهي عرض فقط ولا تختلط مع مراحل الاعتماد الجديدة.'}; return notes[activeWindow]||''; }
  function updateKpis(rows){ const set=(id,v)=>{if($(id))$(id).textContent=v;}; set('opKpiWindowV288',rows.length); set('opKpiUrgentV288',rows.filter(o=>o.priority==='عاجل').length); set('opKpiImportantV288',rows.filter(o=>o.priority==='مهم').length); set('opKpiAmountV288',money(rows.reduce((s,o)=>s+num(o.approved_amount||o.estimated_amount),0))); set('opKpiUpdatedV288',new Date().toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'})); updateCounts(); if($('opWindowTitleV288'))$('opWindowTitleV288').textContent=stageMap[activeWindow]||''; if($('opWindowNoteV288'))$('opWindowNoteV288').textContent=windowNote(); const form=$('opFormCardV288'); if(form) form.style.display=(activeWindow==='legacy'||activeWindow==='closed')?'none':''; }
  function renderProfessionalOrdersV288(){ ensureStyle();ensureBadge();fillProjectFilter(); const rows=filtered(); updateKpis(rows); const head=$('opOrdersHeadV288'),body=$('opOrdersBodyV288'); if(!head||!body)return; head.innerHTML='<tr><th>رقم الأوردر</th><th>المشروع</th><th>العنوان / التفاصيل</th><th>الأولوية</th><th>الحالة</th><th>المرحلة</th><th>المبلغ</th><th>مقدم الطلب</th><th>التاريخ</th><th>الإجراءات</th></tr>'; body.innerHTML=rows.map(o=>`<tr><td><b>${esc(o.order_no)}</b><br><span class="muted">قروب: ${esc(o.group_no||'-')}</span></td><td>${esc(o.project_name||projectName(o.project_id)||'-')}</td><td class="desc"><b>${esc(o.title||'-')}</b><br><span class="muted">${esc(o.description||'')}</span></td><td><span class="badge ${priorityClass[o.priority]||''}">${esc(o.priority||'عادي')}</span></td><td><span class="stage-chip-v288">${esc(o.legacy?(o.raw?.['حالة التنفيذ']||'قديم'):(statusMap[o.status]||o.status))}</span></td><td>${esc(o.legacy?'الأرشيف القديم':(stageMap[o.current_stage]||o.current_stage||'-'))}</td><td>${money(o.approved_amount||o.estimated_amount)} ر.س</td><td>${esc(o.requester_name||'-')}</td><td>${esc(String(o.created_at||'').slice(0,10))}</td><td class="row-actions">${actions(o)}</td></tr>`).join('')||'<tr><td colspan="10">لا توجد أوردرات في هذه النافذة</td></tr>'; }
  window.renderProfessionalOrdersV288=renderProfessionalOrdersV288;
  window.setOrdersWindowV288=function(k){ activeWindow=k; const sec=$('orders'); if(sec){ sec.innerHTML=adminHtml(); fillProjectSelect('opProjectV288'); fillProjectFilter(); } renderProfessionalOrdersV288(); };
  function renderLogsBox(orderId){ const box=$('opLogBoxV288'); if(!box)return; if(!orderId){box.classList.add('hidden');box.innerHTML='';return;} box.classList.remove('hidden'); const logs=logsCache.filter(l=>String(l.order_id)===String(orderId)); box.innerHTML='<h3>سجل حركة الأوردر</h3>'+(logs.map(l=>`<div class="order-log-item-v288"><b>${esc(l.action)}</b><br><span class="muted">${esc(l.user_name||'-')} - ${esc(String(l.created_at||'').slice(0,16).replace('T',' '))}</span><br>${esc(l.note||'')}</div>`).join('')||'<div class="muted">لا يوجد سجل حركة بعد</div>'); }
  function exportProfessionalOrdersV288(){ const rows=filtered(); const headers=['النافذة','رقم الأوردر','رقم القروب','المشروع','العنوان','الوصف','النوع','الأولوية','الحالة','المرحلة','المبلغ المتوقع','المبلغ المعتمد','طريقة الدفع','المورد','رقم الفاتورة','مقدم الطلب','التاريخ']; const xmlRows=rows.map(o=>[stageMap[activeWindow],o.order_no,o.group_no,o.project_name,o.title,o.description,o.order_type,o.priority,o.legacy?(o.raw?.['حالة التنفيذ']||'قديم'):(statusMap[o.status]||o.status),o.legacy?'الأرشيف القديم':(stageMap[o.current_stage]||o.current_stage),o.estimated_amount,o.approved_amount,o.payment_method,o.supplier_name,o.invoice_no,o.requester_name,String(o.created_at||'').slice(0,10)]); const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Orders"><Table><Row>${headers.map(h=>`<Cell><Data ss:Type="String">${esc(h)}</Data></Cell>`).join('')}</Row>${xmlRows.map(r=>`<Row>${r.map(c=>`<Cell><Data ss:Type="String">${esc(c??'')}</Data></Cell>`).join('')}</Row>`).join('')}</Table></Worksheet></Workbook>`; const blob=new Blob(['\ufeff'+xml],{type:'application/vnd.ms-excel'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='orders_'+activeWindow+'.xls'; a.click(); URL.revokeObjectURL(a.href); }
  window.exportProfessionalOrdersV288=exportProfessionalOrdersV288;
  const oldShow=window.showPage; window.showPage=function(id,btn){ if(typeof oldShow==='function')oldShow(id,btn); if(id==='orders')setTimeout(injectAdmin,80); };
  const oldSup=window.showSupervisorWindow; window.showSupervisorWindow=function(id,btn){ if(typeof oldSup==='function')oldSup(id,btn); if(id==='supOrders')setTimeout(loadProfessionalOrdersV288,50); };
  document.addEventListener('DOMContentLoaded',function(){ ensureBadge();ensureStyle();setTimeout(()=>{injectAdmin();injectSupervisor();},900); });
})();
