from pathlib import Path
import subprocess, sys, re
root=Path(__file__).parent
mod=(root/'tasneef_unified_employee_excel_v10811.js').read_text(encoding='utf-8')
admin=(root/'admin.html').read_text(encoding='utf-8')
checks=[]
def check(name, cond): checks.append((name,bool(cond)))
check('Build V10811 موجود', 'V10811-UNIFIED-EXCEL-EXACT-FILTER-STYLED' in admin)
check('ملف V10811 محمل', 'tasneef_unified_employee_excel_v10811.js?v=10811-exact-filter-styled' in admin)
check('ملف V10810 غير محمل', 'tasneef_unified_employee_excel_v10810.js?v=' not in admin)
check('كاش app محدث', 'app.js?v=10811-unified-excel-exact-filter-styled' in admin)
check('ExcelJS يُحمّل عند الطلب', 'exceljs@4.4.0/dist/exceljs.min.js' in mod and 'loadExcelJs' in mod)
check('لا يعتمد على XLSX لكتابة الملف', 'XLSX.writeFile' not in mod)
check('الحفظ بصيغة xlsx عبر ExcelJS', 'wb.xlsx.writeBuffer()' in mod)
check('الفلتر الدقيق يبنى من بيانات العمال نفسها', 'sourceMatchesExactFilter' in mod and 'selectedKeys=new Set(workers.filter' in mod)
check('نتيجة التصدير تقيد بالمفاتيح المختارة', 'details.filter(x=>selectedKeys.has(x.employeeKey))' in mod)
check('فلتر الفئة دقيق', 'if(f.role&&roleGroup(w)!==f.role)return false' in mod)
check('فلتر النشط دقيق', "if(f.status==='active'&&!active)return false" in mod)
check('فلتر الموقوف دقيق', "if(f.status==='inactive'&&active)return false" in mod)
check('البحث مطابق لشاشة العمال', 'workerCode(w),workerName(w),workerIqamaName(w),workerIqamaNo(w),workerRole(w)' in mod)
check('البحث لا يضيف المشروع أو المشرف من خارج الشاشة', 'sourceMatchesExactFilter' in mod and 'r.projects.join' not in mod)
check('المشرف مصنف', "return'supervisor'" in mod)
check('العامل مصنف', "return'worker'" in mod)
check('الحارس مصنف بمرادفاته', all(x in mod for x in ["r.includes('حارس')","r.includes('حراسه')","r.includes('security')","r.includes('guard')"]))
check('كل الفئات موضحة بأنها تشمل العمال والحراس والمشرفين', 'العمال والحراس والمشرفون' in mod)
check('المشرف يظهر أولا', "a.roleGroup==='supervisor'?0:1" in mod)
check('الحارس بعد العامل', 'roleOrder:{worker:1,guard:2,technician:3,employee:4}' in mod)
check('الترتيب حسب المشروع', "a.primaryProject.localeCompare(b.primaryProject,'ar')" in mod)
headers="const headers=['رقم','أيدي الموظف','الشهر','اسم الموظف في الإقامة','اسم الموظف الحركي','رقم الإقامة','مكان العمل','الوظيفة','بداية الدوام','نهاية الدوام','أيام الحضور','أيام الغياب','الأيام المستحقة','قيمة الرواتب الأساسية','البدلات','الإجمالي','إجمالي الراتب على أيام الفترة','العمولات','الخصومات','جبر الكسور','خصم السلف','الصافي','ملاحظات']"
check('الخانات الأساسية مطابقة للملف المرجعي', headers in mod)
check('عدد أعمدة الكشف الرئيسي 23', "addStyledSheetHeader(ws,'W'" in mod and 'ws.columns=[6,13,11,29,23,16,25,13,21,21,12,11,13,16,12,13,21,12,12,12,12,14,28]' in mod)
check('لا يوجد عمود منفصل يغيّر شكل القالب', "'مكان العمل','اسم المشرف','الوظيفة'" not in mod)
check('العنوان مطابق كشف الرواتب', "'كشف الرواتب'" in mod)
check('لون الرأس مطابق', "'0B5D49'" in mod)
check('لون الحدود مطابق', "BORDER_COLOR='B8D6CD'" in mod)
check('خط القالب Calibri', "name:'Calibri'" in mod)
check('حجم العنوان 22', 'size:22' in mod)
check('RTL مفعل', 'rightToLeft:true' in mod and "readingOrder:'rtl'" in mod)
check('التجميد عند الصف الثالث', "ySplit:3" in mod)
check('ألوان صفوف متبادلة', "i%2?'F7FBF9':'EEF7F4'" in mod)
check('صف المشرف مميز', "isSup?'DCEFE8'" in mod)
check('بداية الدوام من الحضور', 'firstWorked?dateTimeLabel(firstWorked.date,firstWorked.firstIn)' in mod)
check('نهاية الدوام من الحضور', 'lastWorked?dateTimeLabel(lastWorked.date,lastWorked.lastOut)' in mod)
check('مصدر الحضور جدول attendance', "safeFetch('attendance'" in mod)
check('الزيارة اليومية تعرض اسم المشرف', 'i.full?i.name:sup.name' in mod)
check('الدوام الكامل يعرض اسم المشروع', 'i.full?i.name:sup.name' in mod and "t.includes('دوام')" in mod)
check('منع الضغط المتكرر', 'if(btn?.disabled)return' in mod)
check('ربط V10811 هو المسيطر', 'btn.dataset.v10811' in mod and 'window.exportSupervisorEmployeesExcelV10811=exportExcel' in mod)
check('اسم الملف حسب الفلتر', 'كشف_الرواتب_حسب_الفلتر_' in mod)
syntax=subprocess.run(['node','--check',str(root/'tasneef_unified_employee_excel_v10811.js')],capture_output=True,text=True)
check('JavaScript Syntax صحيح', syntax.returncode==0)
if syntax.returncode: print(syntax.stderr)
passed=sum(v for _,v in checks)
for name,ok in checks: print(('PASS' if ok else 'FAIL')+' | '+name)
print(f'RESULT {passed}/{len(checks)}')
sys.exit(0 if passed==len(checks) else 1)
