from pathlib import Path
import subprocess, sys
root=Path(__file__).resolve().parent
excel=(root/'tasneef_unified_employee_excel_v10811.js').read_text(encoding='utf-8')
att=(root/'tasneef_core_attendance_unified_source_v430.js').read_text(encoding='utf-8')
admin=(root/'admin.html').read_text(encoding='utf-8')
checks=[]
def check(name,cond):
    checks.append((name,bool(cond)))

check('build V10812', 'V10812-WADDAH-FORMULA-ATTENDANCE-RANGE' in admin)
check('app cache V10812', 'app.js?v=10812-waddah-formula-attendance-range' in admin)
check('attendance cache V10812', 'tasneef_core_attendance_unified_source_v430.js?v=10812-date-range' in admin)
check('excel cache V10812', 'tasneef_unified_employee_excel_v10811.js?v=10812-waddah-formulas' in admin)
check('excel module version', "const VERSION='V10812'" in excel)
check('role fields include role_type', 'w?.role_type' in excel)
check('role fields include worker_role', 'w?.worker_role' in excel)
check('role fields include employee_type', 'w?.employee_type' in excel)
check('role text combines fields', "workerRoleFields(w).join(' | ')" in excel)
check('supervisor detects combined roles', 'norm(workerRoleText(w))' in excel)
check('Waddah partial name helper', 'findSupervisorWorker' in excel and 'n.includes(t)||t.includes(n)' in excel)
check('supervisor fallback row', "role_type:'مشرف'" in excel)
check('distribution supervisors included', 'supervisorProjects.forEach' in excel)
check('all unified supervisors included', 'workers.filter(w=>isSupervisor(w)' in excel)
check('exact detail filter', 'detailMatchesExactFilter' in excel)
check('old selected key gate removed', 'selectedKeys.has' not in excel)
check('gross formula ready', 'formula:`N${rn}+O${rn}`' in excel)
check('period formula ready', 'formula:`IFERROR(P${rn}/${daysInMonth}*M${rn},0)`' in excel)
check('net formula ready', 'formula:`Q${rn}+R${rn}-S${rn}+T${rn}-U${rn}`' in excel)
check('total formulas ready', 'formula:`SUM(${letter}${firstDataRow}:${letter}${lastDataRow})`' in excel)
check('automatic recalculation', "calcMode='auto'" in excel and 'fullCalcOnLoad=true' in excel)
check('workbook remains editable', 'ws.protect' not in excel and 'workbook.protect' not in excel)
check('formula guide', 'المعادلات الجاهزة' in excel)
check('editable guide', 'قابلية التعديل' in excel)
check('green payroll style preserved', "ARGB('0B5D49')" in excel)
check('RTL preserved', 'rightToLeft:true' in excel)
check('worker role filter preserved', "return'worker'" in excel)
check('guard role filter preserved', "return'guard'" in excel)
check('supervisor role filter preserved', "return'supervisor'" in excel)
check('from date input', 'id="cu427From"' in att)
check('to date input', 'id="cu427To"' in att)
check('selected attendance date retained', 'id="cu427Date"' in att)
check('range title', 'cu427RangeTitle' in att)
check('attendance range gte', ".gte('attendance_date',from)" in att)
check('attendance range lte', ".lte('attendance_date',to)" in att)
check('multi-month distributions', 'rangeMonths(loadFrom,loadTo,f.date)' in att)
check('date range helper', 'function rangeDates(from,to)' in att)
check('month range helper', 'function rangeMonths(from,to,extra)' in att)
check('selected month daily rows', 'currentRows(true)' in att)
check('range rows separate', 'currentRows(false)' in att)
check('save affects selected day workers', 'const rows=currentRows(true)' in att)
check('range CSV filename', "attendance_'+f.from+'_to_'+f.to" in att)
check('invalid range validation', 'f.to<f.from' in att)
check('maximum range protection', 'مدة لا تتجاوز 369 يومًا' in att)
check('old month input removed', 'id="cu427Month"' not in att)
check('no SQL dependency added', 'supabase_' not in ''.join([excel,att]))

# Syntax checks
for f in ['tasneef_unified_employee_excel_v10811.js','tasneef_core_attendance_unified_source_v430.js']:
    r=subprocess.run(['node','--check',str(root/f)],capture_output=True,text=True)
    check('syntax '+f, r.returncode==0)

passed=sum(v for _,v in checks)
for name,ok in checks:
    print(('PASS' if ok else 'FAIL')+' | '+name)
print(f'RESULT {passed}/{len(checks)}')
if passed!=len(checks): sys.exit(1)
