from pathlib import Path
import re, subprocess, sys, json
ROOT=Path(__file__).resolve().parent
js=(ROOT/'tasneef_contracts_services_editor_v10807.js').read_text('utf-8')
proj=(ROOT/'tasneef_projects_clean_v390.js').read_text('utf-8')
html=(ROOT/'admin.html').read_text('utf-8')
css=(ROOT/'tasneef_contracts_services_editor_v10807.css').read_text('utf-8')
sql=(ROOT/'supabase_contracts_projects_sync_alerts_v10815.sql').read_text('utf-8')
pre=(ROOT/'supabase_contracts_projects_sync_alerts_preflight_v10815.sql').read_text('utf-8')
verify=(ROOT/'supabase_contracts_projects_sync_alerts_verify_v10815.sql').read_text('utf-8')
checks=[]
def ck(name, cond): checks.append((name,bool(cond)))

# JavaScript syntax
for name in ['tasneef_contracts_services_editor_v10807.js','tasneef_projects_clean_v390.js','app.js']:
    r=subprocess.run(['node','--check',str(ROOT/name)],capture_output=True,text=True)
    ck('JS syntax '+name,r.returncode==0)

ck('V10815 build in HTML','V10815-CONTRACTS-PROJECTS-DIRECT-SYNC-SMART-ALERTS' in html)
ck('single contracts editor script',html.count('tasneef_contracts_services_editor_v10807.js?v=10815')==1)
ck('project module cache bumped','tasneef_projects_clean_v390.js?v=10815-direct-contract-sync' in html)
ck('dashboard smart alerts root','id="contractDashboardAlerts"' in html and 'تنبيهات العقود والخدمات' in html)
ck('stopped contract filter','value="stopped">متوقف — لم يجدد العقد' in html)
ck('strict safe integer project ID','Number.isSafeInteger(x)' in js)
ck('project master loaded by id',"safeSelect('projects',q=>q.select('*').eq('id',ID(projectId))" in js)
ck('no project link by name',not re.search(r"contracts\.project_name\s*=\s*projects\.name|project_name\s*===\s*.*name",js))
ck('project shared fields in contract editor', all(x in js for x in ["projectField('name'", "projectField('project_code'", "projectField('responsible_name'", "projectField('contact_phone'"]))
ck('project shared fields save diff','collectProjectChanges' in js and "'responsible_name'" in js and "'contact_phone'" in js)
ck('optimistic project conflict check','p_expected_project_updated_at' in js and 'تم تعديل بيانات المشروع من مستخدم آخر' in js)
ck('cross section project event','tasneef:project-updated' in js and 'tasneef:project-updated' in proj)
ck('stopped project stays in contracts','is-stopped-project' in js and 'محفوظ للعرض التاريخي' in js)
ck('stopped project blocks new service','لا يمكن تنفيذ خدمة جديدة لمشروع موقوف' in js)
ck('project section has shared fields',all(x in proj for x in ['pr387ProjectCode','pr387ProjectType','pr387City','pr387District','pr387Responsible','pr387ContactPhone']))
ck('project section updated_at conflict',"data-updated-at" in proj and "eq('updated_at',expected)" in proj)
ck('project status filter includes stopped','pr387FilterStatusV10815' in proj and 'المتوقفة' in proj)
ck('contracts renewal RPC v10815',"rpc('renew_project_contract_v10815'" in js)
ck('contracts nonrenew RPC v10815',"rpc('non_renew_project_contract_v10815'" in js)
ck('service execution RPC v10815',"rpc('execute_annual_service_v10815'" in js)
ck('save RPC v10815',"rpc('save_contracts_services_editor_v10815'" in js)
ck('decision refreshes affected project',js.count('await refreshAffectedProject()')>=4)
ck('alert priorities',all(x in js for x in ['عاجل','مرتفع','متوسط','منخفض','محسوم']))
ck('alert summaries',all(x in js for x in ['عقود منتهية','تنتهي خلال 7 أيام','تنتهي خلال 30 يومًا','تنتهي خلال 60 يومًا','خدمات متأخرة','متوقفة لعدم التجديد']))
ck('alert filters active/resolved','التنبيهات النشطة' in js and 'التنبيهات المحسومة' in js)
ck('service overdue alert cards','service_overdue' in js and 'annual_service:' in js)
ck('alert detail lazy load',"get_contract_alert_detail_v10815" in js and 'يتم تحميل التفاصيل عند فتح التنبيه فقط' in js)
ck('responsive alert CSS','cs-alert-summary-v10815' in css and '@media(max-width:560px)' in css)

# SQL requirements
ck('main SQL transaction',re.search(r'\bbegin;[\s\S]*\bcommit;',sql,re.I) is not None)
ck('projects id asserted bigint',"v_target<>'bigint'" in sql)
ck('project_id tables aligned',all(x in sql for x in ['contracts','contract_services','contract_attachments','contract_expiry_notifications','project_contract_smart','contract_change_logs','monthly_distribution']))
ck('project ID backup table','contract_project_id_backup_v10815' in sql and 'to_jsonb(t)' in sql)
ck('invalid values reported','contract_identifier_issues_v10815' in sql and "!~''^[0-9]+$''" in sql)
ck('alignment fails atomically','v_fail>0 then raise exception' in sql)
ck('V10815 project RPC params bigint',all(x in sql for x in ['save_contracts_services_editor_v10815(\n  p_project_id bigint','p_service_id text,p_project_id bigint','renew_project_contract_v10815(\n  p_project_id bigint','non_renew_project_contract_v10815(\n  p_project_id bigint']))
ck('direct bigint project joins','join public.projects p on p.id=n.project_id' in sql and 'join public.projects p on p.id=s.project_id' in sql)
ck('no V10815 text project parameter','p_project_id text' not in sql)
ck('permission helper','contract_user_has_permission_v10815' in sql)
ck('renew server permission',"'contracts.renew'" in sql)
ck('nonrenew server permissions',"'contracts.non_renew'" in sql and "'projects.stop_from_contract'" in sql)
ck('old action RPCs revoked',sql.count('revoke execute on function public.')>=4)
ck('unique notification key','uq_contract_expiry_notification_key_v10815' in sql)
ck('duplicate alerts resolved not deleted',"resolution='duplicate_merged'" in sql and not re.search(r'delete\s+from\s+public\.contract_expiry_notifications',sql,re.I))
ck('notification key includes contract and end date',"concat('contract_expiry:',c.id,':',c.end_date)" in sql)
ck('resolved notifications preserved',"status='resolved'" in sql and 'resolved_notifications' in verify)
ck('renew wrapper transaction result','transaction_complete' in sql and 'renew_project_contract_v10814' in sql)
ck('nonrenew wrapper transaction result','non_renew_project_contract_v10814' in sql and 'p_stop_date' in sql)
ck('stopped projects dashboard metric','stopped_nonrenew' in sql)
ck('overdue services union alerts',"'service'::text alert_kind" in sql and "'service_overdue'::text status" in sql)
ck('preflight is read safe','alter table' not in pre.lower() and 'update public.' not in pre.lower() and 'delete from public.' not in pre.lower())
ck('verify checks active duplicate keys','active_duplicate_keys' in verify)
ck('verify checks history','historical_contracts' in verify and 'historical_services' in verify and 'historical_attachments' in verify)
ck('no historical table deletes',not re.search(r'delete\s+from\s+public\.(contracts|contract_services|contract_attachments|projects|contract_change_logs)',sql,re.I))
ck('balanced dollar quotes',sql.count('$$')%2==0)
ck('no browser alert prompt confirm',not re.search(r'\b(alert|prompt|confirm)\s*\(',js))

failed=[n for n,v in checks if not v]
lines=[f"V10815 static acceptance tests: {len(checks)-len(failed)}/{len(checks)} passed",'']
for n,v in checks: lines.append(('PASS ' if v else 'FAIL ')+n)
(ROOT/'CONTRACTS_PROJECTS_SYNC_ALERTS_STATIC_TEST_V10815.txt').write_text('\n'.join(lines)+'\n','utf-8')
print('\n'.join(lines))
if failed: sys.exit(1)
